export interface Brewery {
  name: string;
  neighbourhood: string;
  founded: number;
  signatureBeer: string;
  style: string;
  tagline: string;
  fact: string;
  emoji: string;
}

export const BANGALORE_BREWERIES: Brewery[] = [
  {
    name: "Toit",
    neighbourhood: "Indiranagar",
    founded: 2010,
    signatureBeer: "Toit Weiss",
    style: "Hefeweizen",
    tagline: "Bengaluru's original craft beer destination.",
    fact: "Toit was one of India's first microbreweries when it opened in 2010. Its long garden tables and Weiss on tap became the blueprint for everything that followed in Indiranagar.",
    emoji: "🍺",
  },
  {
    name: "Windmills Craftworks",
    neighbourhood: "Whitefield",
    founded: 2013,
    signatureBeer: "Hefeweizen",
    style: "Wheat Beer",
    tagline: "Where East Bangalore discovered craft beer.",
    fact: "Windmills in Whitefield was one of the first microbreweries to open outside the MG Road belt, proving that craft beer could travel to the tech corridor. Their Hefeweizen has a devoted following.",
    emoji: "🌾",
  },
  {
    name: "The Biere Club",
    neighbourhood: "Lavelle Road",
    founded: 2012,
    signatureBeer: "Belgian Wit",
    style: "Witbier",
    tagline: "Where Bengaluru's old money drinks new beer.",
    fact: "The Biere Club on Lavelle Road brought the Belgian pub aesthetic to Bangalore, including imported taps and a Belgian-trained brewmaster. Their barrel-aged releases have become collector items.",
    emoji: "🇧🇪",
  },
  {
    name: "Byg Brewski",
    neighbourhood: "Hennur",
    founded: 2013,
    signatureBeer: "Whiskey Wheat",
    style: "American Wheat Ale",
    tagline: "The sprawling garden pub that Bengaluru needed.",
    fact: "Byg Brewski's Hennur location is one of Bangalore's largest pub gardens, with space for over 1,000 guests spread across themed zones. Their Whiskey Wheat blends two great things about life.",
    emoji: "🌻",
  },
  {
    name: "Biergarten",
    neighbourhood: "Vittal Mallya Road",
    founded: 2014,
    signatureBeer: "Munich Dunkel",
    style: "Dark Lager",
    tagline: "A Munich Biergarten, in the middle of Bangalore.",
    fact: "Biergarten on Vittal Mallya Road consciously replicates the Bavarian beer garden tradition, with long communal tables, pretzels, and a Munich Dunkel that is consistently the best dark lager in the city.",
    emoji: "🥨",
  },
  {
    name: "Arbor Brewing Company",
    neighbourhood: "Koramangala",
    founded: 2014,
    signatureBeer: "Spark Plug Coffee Stout",
    style: "Coffee Stout",
    tagline: "Michigan craft culture, Koramangala soul.",
    fact: "Arbor Brewing originated in Ann Arbor, Michigan. The Bangalore outpost brought their American craft philosophy with it, including a Spark Plug Coffee Stout that combines two of Bengaluru's great passions.",
    emoji: "🌳",
  },
  {
    name: "Ironhill",
    neighbourhood: "HSR Layout",
    founded: 2019,
    signatureBeer: "Mango Sour",
    style: "Fruit Sour",
    tagline: "The brewery that thinks like a tech startup.",
    fact: "Ironhill is reportedly India's largest brewery by capacity. Their Mango Sour has been a breakout success, showing that Bangalore drinkers are ready for acidic, fruit-forward styles.",
    emoji: "⚙️",
  },
  {
    name: "Geist Brewing Co",
    neighbourhood: "Jeevan Bhima Nagar",
    founded: 2018,
    signatureBeer: "Kölsch",
    style: "German Kölsch",
    tagline: "German brewing discipline, Bengaluru precision.",
    fact: "Geist is one of the few Indian breweries seriously pursuing authentic German lager styles, including a Kölsch fermented cold and lagered for weeks. Brewmaster Hans has brought a rare commitment to process.",
    emoji: "🇩🇪",
  },
  {
    name: "Kati Patang",
    neighbourhood: "HSR Layout",
    founded: 2017,
    signatureBeer: "Lemon Gose",
    style: "Gose / Salt Beer",
    tagline: "India's most playful beer, seriously made.",
    fact: "Kati Patang was among the first Indian breweries to produce a Gose — a tart, salty German style that was nearly extinct until craft beer revived it. Their Lemon Gose is a perfect summer afternoon drink.",
    emoji: "🪁",
  },
  {
    name: "7 Rivers Brewing",
    neighbourhood: "Indiranagar",
    founded: 2016,
    signatureBeer: "Irish Red Ale",
    style: "Irish Red",
    tagline: "Seven rivers of Karnataka, one great pint.",
    fact: "7 Rivers takes its name from Karnataka's seven major rivers. Their Irish Red Ale is a tribute to the malt-forward tradition and is one of the most consistent pours in Indiranagar.",
    emoji: "🌊",
  },
  {
    name: "Big Brewing Co",
    neighbourhood: "Marathahalli",
    founded: 2016,
    signatureBeer: "IPA",
    style: "India Pale Ale",
    tagline: "The East Bangalore institution.",
    fact: "Big Brewing Co was one of the early breweries to plant a flag in Marathahalli, serving the IT corridor crowd a properly hoppy IPA in an era when most Bangalore breweries were avoiding the style.",
    emoji: "🏭",
  },
  {
    name: "Bangalore Brewing Company",
    neighbourhood: "MG Road",
    founded: 2015,
    signatureBeer: "American Pale Ale",
    style: "Pale Ale",
    tagline: "The address is the identity.",
    fact: "Bangalore Brewing Company wears the city's name proudly. Their American Pale Ale — balanced, citrusy, easy-drinking — is a deliberate effort to make craft beer accessible to someone ordering their first pint.",
    emoji: "🏙️",
  },
  {
    name: "Effingut Brewerkz",
    neighbourhood: "Koramangala",
    founded: 2016,
    signatureBeer: "Belgian Strong Ale",
    style: "Belgian Strong",
    tagline: "Unfiltered beer and unfiltered opinions.",
    fact: "Effingut built a loyal following through a rotating experimental tap list alongside their core range. Their Belgian Strong Ale routinely shows up on best-in-Bangalore lists and is the drink for serious evenings.",
    emoji: "⚡",
  },
  {
    name: "Vapour",
    neighbourhood: "Cunningham Road",
    founded: 2013,
    signatureBeer: "Draught Wheat",
    style: "American Wheat",
    tagline: "Old Bengaluru, new beer.",
    fact: "Vapour on Cunningham Road was one of the bars that proved Bengaluru's traditional pub belt could embrace craft beer. Their Draught Wheat was the gateway beer for hundreds of Bengaluru's early craft converts.",
    emoji: "💨",
  },
  {
    name: "Brew & Barbeque",
    neighbourhood: "Jayanagar",
    founded: 2017,
    signatureBeer: "Amber Ale",
    style: "Amber Ale",
    tagline: "South Bangalore finally got its brewery.",
    fact: "Brew & Barbeque brought craft beer to Jayanagar, a neighbourhood better known for its idli than its IPAs. Their Amber Ale pairs brilliantly with the smoked meats that come out of their open kitchen.",
    emoji: "🔥",
  },
];
