export interface Park {
  name: string;
  kannada: string;
  area: string;
  established: number;
  photo: string;
  fact: string;
  bestTime: string;
  lat: number;
  lng: number;
}

export const BANGALORE_PARKS: Park[] = [
  {
    name: "Cubbon Park",
    kannada: "ಕಬ್ಬನ್ ಪಾರ್ಕ್",
    area: "300 acres",
    established: 1870,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Cubbon_Park_W.jpg/1280px-Cubbon_Park_W.jpg",
    fact: "Home to 6,000 trees and over 68 species of plants. The city's green lungs and its favourite Sunday morning destination.",
    bestTime: "Early morning (6 to 8am): when walkers, joggers, and bird-watchers have it to themselves",
    lat: 12.9763, lng: 77.5929,
  },
  {
    name: "Lalbagh Botanical Garden",
    kannada: "ಲಾಲ್‌ಬಾಗ್ ಸಸ್ಯೋದ್ಯಾನ",
    area: "240 acres",
    established: 1760,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Glasshouse_and_fountain_at_lalbagh.jpg/1280px-Glasshouse_and_fountain_at_lalbagh.jpg",
    fact: "Founded by Hyder Ali in 1760. Contains a 3000 million year old rock formation and trees from around the world.",
    bestTime: "Republic Day and Independence Day: the flower show is legendary",
    lat: 12.9507, lng: 77.5843,
  },
  {
    name: "Bannerghatta Biological Park",
    kannada: "ಬನ್ನೇರುಘಟ್ಟ ಜೈವಿಕ ಉದ್ಯಾನ",
    area: "25,000 acres",
    established: 1971,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Lurking_tiger.jpg/1280px-Lurking_tiger.jpg",
    fact: "25,000 acres of protected forest just 22km from the city centre. Where tigers, elephants, and leopards roam.",
    bestTime: "Morning safari: the jungle is alive before 9am",
    lat: 12.7976, lng: 77.5784,
  },
  {
    name: "Nandi Hills",
    kannada: "ನಂದಿ ಬೆಟ್ಟ",
    area: "600+ acres",
    established: 1000,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Sunrise_%40_Nandi_Hills%2C_Bangalore%2C_India.jpg/1280px-Sunrise_%40_Nandi_Hills%2C_Bangalore%2C_India.jpg",
    fact: "60km from Bangalore at 1,478m. Tipu Sultan's summer retreat is now Bangalore's favourite weekend sunrise spot.",
    bestTime: "Sunrise: arrive by 5:30am for the cloud sea view",
    lat: 13.3702, lng: 77.6835,
  },
  {
    name: "Turahalli Forest",
    kannada: "ತುರಹಳ್ಳಿ ಕಾಡು",
    area: "644 acres",
    established: 1900,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Thurahalli%2C_Bengaluru%2C_Karnataka_560062%2C_India_-_panoramio_%282%29.jpg/1280px-Thurahalli%2C_Bengaluru%2C_Karnataka_560062%2C_India_-_panoramio_%282%29.jpg",
    fact: "The last surviving dry deciduous forest inside Bangalore's city limits. A hidden trail running sanctuary.",
    bestTime: "Early morning trail runs: peaceful, local, and gloriously green",
    lat: 12.8875, lng: 77.5484,
  },
  {
    name: "Bugle Rock Park",
    kannada: "ಬ್ಯೂಗಲ್ ರಾಕ್ ಪಾರ್ಕ್",
    area: "8 acres",
    established: 1927,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Bugle_Rock_Kahale.jpg/1280px-Bugle_Rock_Kahale.jpg",
    fact: "Built around a 3,000 million year old Archaean gneissic rock in Basavanagudi. One of Bangalore's oldest and most beloved neighbourhood parks.",
    bestTime: "Evening: the rock glows amber at sunset and the bats emerge at dusk",
    lat: 12.9408, lng: 77.5685,
  },
  {
    name: "Hesaraghatta Grasslands",
    kannada: "ಹೇಸರಘಟ್ಟ ಹುಲ್ಲುಗಾವಲು",
    area: "5,000+ acres",
    established: 1894,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Hesaraghatta_dry_lakebed.jpg/1280px-Hesaraghatta_dry_lakebed.jpg",
    fact: "One of India's most important open grassland ecosystems just outside Bangalore. Home to the endangered Great Indian Bustard and wolves.",
    bestTime: "Winter mornings (November to February): the grasslands come alive with raptors and migratory birds",
    lat: 13.1285, lng: 77.4761,
  },
  {
    name: "Sankey Tank Garden",
    kannada: "ಸ್ಯಾಂಕಿ ಕೆರೆ ಉದ್ಯಾನ",
    area: "15 acres",
    established: 1882,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sankey_Tank.jpg/1280px-Sankey_Tank.jpg",
    fact: "The garden around Sankey Tank is one of Bangalore's most cherished morning spots. Joggers, yoga practitioners, and filter coffee walkers share it every dawn.",
    bestTime: "Early morning: the mist over the tank before 7am is ethereal",
    lat: 13.0107, lng: 77.5796,
  },
  {
    name: "Banashankari Temple Park",
    kannada: "ಬನಶಂಕರಿ ದೇವಸ್ಥಾನ ಉದ್ಯಾನ",
    area: "20 acres",
    established: 1915,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Sri_Banashankari_Temple%2C_Bengaluru_%282024%29_08.jpg/1280px-Sri_Banashankari_Temple%2C_Bengaluru_%282024%29_08.jpg",
    fact: "Surrounds the ancient Banashankari temple in South Bangalore. The temple tank, old trees, and quiet paths make it a sacred natural refuge in the city.",
    bestTime: "Early morning puja time: the fragrance of flowers and incense fills the air",
    lat: 12.9255, lng: 77.5468,
  },
  {
    name: "GKVK University Campus",
    kannada: "ಜಿ.ಕೆ.ವಿ.ಕೆ. ಆವರಣ",
    area: "1,400 acres",
    established: 1975,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/GKVK_Bangalore.jpg/1280px-GKVK_Bangalore.jpg",
    fact: "The University of Agricultural Sciences campus is one of Bangalore's best-kept secrets: 1,400 acres of farms, orchards, research fields, and forest in the heart of North Bangalore.",
    bestTime: "Weekday mornings: the campus is open, peaceful, and gloriously green",
    lat: 13.0798, lng: 77.5798,
  },
  {
    name: "Jacaranda Avenue",
    kannada: "ಜಕಾರಂಡ ರಸ್ತೆ",
    area: "Tree-lined boulevard",
    established: 1930,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/BGL_Jacaranda.jpg/1280px-BGL_Jacaranda.jpg",
    fact: "Bangalore's famous Jacaranda-lined roads — Bellary Road, MG Road, Cunningham Road — explode in violet-purple every March. The city is briefly another place entirely.",
    bestTime: "March to April: when the Jacaranda is in full bloom and the streets turn purple",
    lat: 12.9755, lng: 77.6080,
  },
  {
    name: "Whitefield Lake Park",
    kannada: "ವೈಟ್‌ಫೀಲ್ಡ್ ಕೆರೆ ಉದ್ಯಾನ",
    area: "30 acres",
    established: 2010,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg/1280px-Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg",
    fact: "A community park around the Whitefield lake that has become the green lung of East Bangalore's IT corridor. Proof that even the tech belt can have natural beauty.",
    bestTime: "Early morning before 8am: joggers, dog walkers, and quiet people enjoying the mist over the lake",
    lat: 12.9731, lng: 77.7494,
  },
  {
    name: "Kengeri Urban Forest",
    kannada: "ಕೆಂಗೇರಿ ನಗರ ಕಾಡು",
    area: "200 acres",
    established: 1985,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Laughing_dove%2C_Turahalli_forest.jpg/1280px-Laughing_dove%2C_Turahalli_forest.jpg",
    fact: "A quiet urban forest in West Bangalore that most residents don't know exists. Home to mongoose, porcupine, and over 80 bird species.",
    bestTime: "Weekday mornings: you may have the entire forest to yourself",
    lat: 12.9068, lng: 77.4836,
  },
  {
    name: "Dodda Alada Mara",
    kannada: "ದೊಡ್ಡ ಆಲದ ಮರ",
    area: "3 acres (canopy)",
    established: 1500,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Dodda_Alada_Mara_banyan_8.jpg/1280px-Dodda_Alada_Mara_banyan_8.jpg",
    fact: "One of the largest banyan trees in the world at Ramohalli, 28km from the city. Its aerial roots cover nearly 3 acres and it is said to be over 400 years old.",
    bestTime: "Early morning on a weekday: the tree is almost entirely yours to explore",
    lat: 12.9253, lng: 77.4354,
  },
  {
    name: "Freedom Park",
    kannada: "ಸ್ವಾತಂತ್ರ್ಯ ಉದ್ಯಾನ",
    area: "22 acres",
    established: 2008,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Freedom_park%2C_Bengaluru.jpg/1280px-Freedom_park%2C_Bengaluru.jpg",
    fact: "Built on the site of Bangalore's old Central Jail where freedom fighters were imprisoned. The original jail walls still stand as a monument to independence.",
    bestTime: "Evenings: the lit-up old jail walls against the night sky are striking",
    lat: 12.9757, lng: 77.5733,
  },
  {
    name: "Butterfly Park",
    kannada: "ಚಿಟ್ಟೆ ಉದ್ಯಾನ",
    area: "7 acres",
    established: 2006,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Butterfly_Park-9-bannerghatta_zoo-bangalore-India.jpg/1280px-Butterfly_Park-9-bannerghatta_zoo-bangalore-India.jpg",
    fact: "India's first butterfly enclosure, inside Bannerghatta Biological Park. Over 20 species of butterflies in a walk-through conservatory with 40,000+ plants.",
    bestTime: "Morning hours: butterflies are most active before the midday heat",
    lat: 12.8020, lng: 77.5787,
  },
  {
    name: "Malleshwaram Park",
    kannada: "ಮಲ್ಲೇಶ್ವರಂ ಉದ್ಯಾನ",
    area: "12 acres",
    established: 1900,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/W._H._Gopal_Park%2C_Bangalore_%282025%29_01.jpg/1280px-W._H._Gopal_Park%2C_Bangalore_%282025%29_01.jpg",
    fact: "The green heart of Malleshwaram, one of Bangalore's oldest and most cherished neighbourhoods. Its shade trees are as old as the layout itself.",
    bestTime: "Sunday mornings: neighbourhood market, filter coffee, and a quiet walk — in that order",
    lat: 13.0025, lng: 77.5638,
  },
  {
    name: "Kamala Nehru Park",
    kannada: "ಕಮಲಾ ನೆಹರೂ ಉದ್ಯಾನ",
    area: "18 acres",
    established: 1960,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Inner_Circle_Park.jpg/1280px-Inner_Circle_Park.jpg",
    fact: "A leafy, unhurried park in Rajajinagar that has been the morning refuge of West Bangalore residents for over six decades. Old trees, quiet paths, minimal crowds.",
    bestTime: "Early morning: peaceful, unhurried, and full of birdsong",
    lat: 13.0069, lng: 77.5559,
  },
  {
    name: "Kadugodi Tree Park",
    kannada: "ಕಾಡುಗೊಡಿ ಮರಗಳ ಉದ್ಯಾನ",
    area: "40 acres",
    established: 1995,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/JP_park_in_Bangalore.jpg/1280px-JP_park_in_Bangalore.jpg",
    fact: "A wooded green belt in Whitefield that serves as a rare wildlife refuge inside East Bangalore's tech corridor. Owls, civets, and jackals have been spotted here.",
    bestTime: "Dusk: when the tech parks empty and the wildlife shift begins",
    lat: 12.9833, lng: 77.7439,
  },
  {
    name: "Jayanagar 4th Block Park",
    kannada: "ಜಯನಗರ ನಾಲ್ಕನೇ ಬ್ಲಾಕ್ ಉದ್ಯಾನ",
    area: "14 acres",
    established: 1960,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Basavanna_Park%2C_Jayanagar%2C_Bangalore_%282024%29.jpg/1280px-Basavanna_Park%2C_Jayanagar%2C_Bangalore_%282024%29.jpg",
    fact: "The beloved neighbourhood park at the heart of Jayanagar 4th Block, one of Bangalore's most admired planned residential areas. Old rain trees shade a community that has walked these paths for three generations.",
    bestTime: "Early morning (6 to 8am): before the heat, when residents do yoga, walk, and chat over coffee",
    lat: 12.9258, lng: 77.5834,
  },
  {
    name: "HAL Heritage Centre & Aerospace Museum",
    kannada: "ಎಚ್‌ಎಎಲ್ ಪರಂಪರೆ ಕೇಂದ್ರ ಮತ್ತು ಏರೋಸ್ಪೇಸ್ ಮ್ಯೂಸಿಯಂ",
    area: "25 acres",
    established: 1973,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/HAL_Heritage_Centre_and_AeroSpace_museum.jpg/1280px-HAL_Heritage_Centre_and_AeroSpace_museum.jpg",
    fact: "India's first aerospace museum, set in the sprawling grounds of Hindustan Aeronautics Limited near Marathahalli. Over 50 vintage aircraft and helicopters are on open-air display, making it a park-cum-museum unlike any other in the country.",
    bestTime: "Weekday mornings: fewer crowds, and the open-air aircraft displays are best in the soft morning light",
    lat: 12.9559, lng: 77.6607,
  },
  {
    name: "Kothanur Dinne Park",
    kannada: "ಕೊಠಾನೂರು ದಿನ್ನೆ ಉದ್ಯಾನ",
    area: "18 acres",
    established: 2005,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Purple-rumped_Sunbird_at_Agrahara_Lake_Bangalore_Karnataka.jpg/1280px-Purple-rumped_Sunbird_at_Agrahara_Lake_Bangalore_Karnataka.jpg",
    fact: "A large green space in North Bangalore's rapidly urbanising Kothanur area. The park is a lifeline for residents seeking respite from the construction boom, and its tree cover supports a surprising variety of garden birds.",
    bestTime: "Morning: listen for purple-rumped sunbirds and tailorbirds in the flowering trees",
    lat: 13.0790, lng: 77.6085,
  },
  {
    name: "Rajarajeshwarinagar Park",
    kannada: "ರಾಜರಾಜೇಶ್ವರಿನಗರ ಉದ್ಯಾನ",
    area: "12 acres",
    established: 1985,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Spotted_dove_Turahalli.jpg/1280px-Spotted_dove_Turahalli.jpg",
    fact: "The community park at the green heart of RR Nagar, one of South-West Bangalore's most densely populated residential zones. Its shady paths are a morning refuge for thousands of families in the surrounding blocks.",
    bestTime: "Evenings: when the entire neighbourhood seems to congregate under the old trees",
    lat: 12.9213, lng: 77.5092,
  },
  {
    name: "Yelahanka New Town Park",
    kannada: "ಯಲಹಂಕ ನ್ಯೂ ಟೌನ್ ಉದ್ಯಾನ",
    area: "20 acres",
    established: 2000,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Brahminy_Kite_%2846675151342%29.jpg/1280px-Brahminy_Kite_%2846675151342%29.jpg",
    fact: "A well-maintained park serving Yelahanka New Town, the planned satellite township north of the city that has grown rapidly around the Kempegowda International Airport corridor. Brahminy kites circle overhead, riding thermals above the open skies of North Bangalore.",
    bestTime: "Early morning: the open skies over Yelahanka make it one of the best places in the city to watch raptors",
    lat: 13.0975, lng: 77.5958,
  },
  {
    name: "Vishwanatha Park (BTM 2nd Stage)",
    kannada: "ವಿಶ್ವನಾಥ ಉದ್ಯಾನ (ಬಿಟಿಎಂ 2ನೇ ಹಂತ)",
    area: "10 acres",
    established: 1990,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Spotted_Owlet_%2830640769088%29.jpg/1280px-Spotted_Owlet_%2830640769088%29.jpg",
    fact: "BTM Layout's main neighbourhood park, tucked into the residential grid of 2nd Stage. Spotted owlets nest in its old trees year after year, delighting birders who know exactly which branch to check at dusk.",
    bestTime: "Dusk: when the spotted owlets emerge from their daytime roosts and the park fills with evening walkers",
    lat: 12.9111, lng: 77.6148,
  },
  {
    name: "Krishnarajapura Lake Park (K.R. Puram)",
    kannada: "ಕೃಷ್ಣರಾಜಪುರ ಕೆರೆ ಉದ್ಯಾನ",
    area: "35 acres",
    established: 2012,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Hanging_bridge_at_KR_puram_railway_station.jpg/1280px-Hanging_bridge_at_KR_puram_railway_station.jpg",
    fact: "A lake park on the eastern edge of Bangalore near K.R. Puram railway station. The restored lake and its bund walkway have become a green anchor in one of the city's busiest transit nodes, where the highway meets the railway.",
    bestTime: "Early morning before the commuter rush: the lake is calm and kingfishers hunt along the shore",
    lat: 13.0055, lng: 77.6997,
  },
  {
    name: "Vijayanagar Park",
    kannada: "ವಿಜಯನಗರ ಉದ್ಯಾನ",
    area: "15 acres",
    established: 1955,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Common_Kingfisher_-_Bangalore%2C_India.jpeg/1280px-Common_Kingfisher_-_Bangalore%2C_India.jpeg",
    fact: "The green heart of Vijayanagar, one of Bangalore's oldest and most beloved western residential areas, developed in the 1950s. The park's mature trees and quiet paths have been a constant through decades of city change around them.",
    bestTime: "Morning: old neighbourhood parks like this one are at their best when the city is still waking up",
    lat: 12.9693, lng: 77.5333,
  },
];
