export interface Lake {
  name: string;
  kannada: string;
  photo: string;
  area: string;
  fact: string;
  restoration: string;
  lat: number;
  lng: number;
}

export const BANGALORE_LAKES: Lake[] = [
  {
    name: "Ulsoor Lake",
    kannada: "ಉಲ್ಸೂರು ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Ulsoor_lake_Bangalore_India.jpg/1280px-Ulsoor_lake_Bangalore_India.jpg",
    area: "123 acres",
    fact: "Home to migratory birds and a beloved rowing club since 1890. The heart of central Bangalore's green escape.",
    restoration: "Recently beautified with walkways and lighting",
    lat: 12.9779, lng: 77.6188,
  },
  {
    name: "Hebbal Lake",
    kannada: "ಹೆಬ್ಬಾಳ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Hebbal_lake_water.jpg/1280px-Hebbal_lake_water.jpg",
    area: "75 acres",
    fact: "A critical stopover for over 100 species of birds including the painted stork and pelican.",
    restoration: "Active bird sanctuary with ongoing conservation",
    lat: 13.0456, lng: 77.5970,
  },
  {
    name: "Sankey Tank",
    kannada: "ಸ್ಯಾಂಕಿ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sankey_Tank.jpg/1280px-Sankey_Tank.jpg",
    area: "37 acres",
    fact: "Built in 1882 by Colonel Sankey. The city's oldest reservoir and now a serene morning walking paradise.",
    restoration: "Lovingly maintained with jogging tracks and beautiful gardens",
    lat: 13.0107, lng: 77.5796,
  },
  {
    name: "Agara Lake",
    kannada: "ಅಗರ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Agara_Lake_%2825279546271%29.jpg/1280px-Agara_Lake_%2825279546271%29.jpg",
    area: "55 acres",
    fact: "Surrounded by HSR Layout. A grassroots community saved and restored this lake from encroachment.",
    restoration: "Community-restored: a model for citizen-led conservation",
    lat: 12.9205, lng: 77.6363,
  },
  {
    name: "Puttenahalli Lake",
    kannada: "ಪುಟ್ಟೇನಹಳ್ಳಿ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg/1280px-Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg",
    area: "22 acres",
    fact: "Rescued from extinction by the Puttenahalli Neighbourhood Lake Improvement Trust. Now a thriving bird habitat.",
    restoration: "The poster child of Bangalore lake restoration: from dead to thriving",
    lat: 12.9003, lng: 77.5963,
  },
  {
    name: "Madiwala Lake",
    kannada: "ಮಡಿವಾಳ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Birds_at_Madiwala_Lake.jpg/1280px-Birds_at_Madiwala_Lake.jpg",
    area: "130 acres",
    fact: "One of Bangalore's oldest lakes. Ancient inscriptions nearby date it to the 10th century.",
    restoration: "Ongoing beautification makes this South Bangalore's green gem",
    lat: 12.9176, lng: 77.6226,
  },
  {
    name: "Lalbagh Lake",
    kannada: "ಲಾಲ್‌ಬಾಗ್ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Glasshouse_and_fountain_at_lalbagh.jpg/1280px-Glasshouse_and_fountain_at_lalbagh.jpg",
    area: "40 acres",
    fact: "Inside Lalbagh Botanical Garden, created by Hyder Ali in 1760. It has been reflecting Bangalore's sky for over 260 years.",
    restoration: "Part of the historic Lalbagh garden, maintained with love for centuries",
    lat: 12.9507, lng: 77.5843,
  },
  {
    name: "Bellandur Lake",
    kannada: "ಬೆಳ್ಳಂದೂರು ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Bellandur_lake_%2821559868065%29.jpg/1280px-Bellandur_lake_%2821559868065%29.jpg",
    area: "890 acres",
    fact: "The largest lake in Bangalore. Now the center of one of India's most ambitious urban lake restoration projects.",
    restoration: "A massive restoration underway: from troubled waters to a future nature reserve",
    lat: 12.9299, lng: 77.6553,
  },
  {
    name: "Varthur Lake",
    kannada: "ವರ್ತೂರು ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Sunset_vtr_lake.jpg/1280px-Sunset_vtr_lake.jpg",
    area: "530 acres",
    fact: "The second largest lake in Bangalore, connected to Bellandur. Both are now at the center of a massive government restoration drive.",
    restoration: "Major desilting and bund restoration underway as part of the BWSSB lake rejuvenation project",
    lat: 12.9417, lng: 77.7053,
  },
  {
    name: "Jakkur Lake",
    kannada: "ಜಕ್ಕೂರು ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Jakkur_lake_and_heronary_.jpg/1280px-Jakkur_lake_and_heronary_.jpg",
    area: "180 acres",
    fact: "One of North Bangalore's most scenic lakes. Sits beside the old Jakkur aerodrome, once used by Hyder Ali's forces.",
    restoration: "Recently developed with walking paths, bird hides, and community gardens",
    lat: 13.0697, lng: 77.5990,
  },
  {
    name: "Kaikondrahalli Lake",
    kannada: "ಕೈಕೊಂಡ್ರಹಳ್ಳಿ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Kaikondanahalli_Lake_Bangalore.jpg/1280px-Kaikondanahalli_Lake_Bangalore.jpg",
    area: "80 acres",
    fact: "A community-restored Sarjapur lake now home to painted storks, pelicans, and over 130 bird species. One of Bangalore's great conservation success stories.",
    restoration: "Citizen-led restoration in 2010 turned a garbage dump into a thriving wetland",
    lat: 12.9178, lng: 77.6832,
  },
  {
    name: "Nagavara Lake",
    kannada: "ನಾಗವಾರ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Jakkur_lake_and_heronary_.jpg/1280px-Jakkur_lake_and_heronary_.jpg",
    area: "170 acres",
    fact: "A historic North Bangalore lake next to the ancient Nageshwara temple. The surrounding park is a beloved evening retreat.",
    restoration: "BBMP beautification with amphitheatre and lighting completed",
    lat: 13.0436, lng: 77.6198,
  },
  {
    name: "Dasarahalli Lake",
    kannada: "ದಸರಹಳ್ಳಿ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg/1280px-Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg",
    area: "95 acres",
    fact: "One of the oldest lakes in the Peenya industrial zone. Now being restored as a green corridor amid the city's industrial heartland.",
    restoration: "Industrial zone lake restoration: proving green can coexist with industry",
    lat: 13.0372, lng: 77.5126,
  },
  {
    name: "Saul Kere",
    kannada: "ಸಾವಲ್ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Agara_Lake_%2825279546271%29.jpg/1280px-Agara_Lake_%2825279546271%29.jpg",
    area: "60 acres",
    fact: "A quiet lake in Whitefield nestled among tech parks. A surprising pocket of nature in the middle of Bangalore's IT corridor.",
    restoration: "Whitefield Rising citizen group has championed its restoration since 2016",
    lat: 12.9698, lng: 77.7499,
  },
  {
    name: "Yediyur Lake",
    kannada: "ಯಡಿಯೂರು ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg/1280px-Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg",
    area: "32 acres",
    fact: "Nestled inside Jayanagar, one of Bangalore's most beloved old neighbourhoods. The lake and its surrounding park are the morning heartbeat of South Bangalore.",
    restoration: "BBMP rejuvenation gave it proper walkways, lighting, and a garden",
    lat: 12.9310, lng: 77.5736,
  },
  {
    name: "Allalasandra Lake",
    kannada: "ಅಲ್ಲಾಲಸಂದ್ರ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Jakkur_lake_and_heronary_.jpg/1280px-Jakkur_lake_and_heronary_.jpg",
    area: "120 acres",
    fact: "A large North Bangalore lake adjacent to the GKVK university campus. The forested university grounds make it one of the greenest pockets north of the city.",
    restoration: "Protected by the University campus, relatively undisturbed",
    lat: 13.0621, lng: 77.5933,
  },
  {
    name: "Rachenahalli Lake",
    kannada: "ರಾಚೇನಹಳ್ಳಿ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Birds_at_Madiwala_Lake.jpg/1280px-Birds_at_Madiwala_Lake.jpg",
    area: "95 acres",
    fact: "A peaceful North Bangalore lake with excellent birdwatching. Spot spot-billed pelicans, painted storks, and purple herons on a quiet morning.",
    restoration: "Citizen groups have fought to keep it free from encroachment",
    lat: 13.0511, lng: 77.6185,
  },
  {
    name: "Vengaiah Lake",
    kannada: "ವೆಂಗಯ್ಯ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sankey_Tank.jpg/1280px-Sankey_Tank.jpg",
    area: "35 acres",
    fact: "Tucked inside Rajajinagar, one of Bangalore's oldest residential layouts. The lake is a quiet gem that most Rajajinagar residents treasure deeply.",
    restoration: "Maintained by BDA with a garden and evening walking path",
    lat: 12.9987, lng: 77.5510,
  },
  {
    name: "Koramangala Tank",
    kannada: "ಕೋರಮಂಗಲ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Kaikondanahalli_Lake_Bangalore.jpg/1280px-Kaikondanahalli_Lake_Bangalore.jpg",
    area: "45 acres",
    fact: "The lake that gives Koramangala its name. 'Kore' means lake in Kannada. The startup capital of India grew around this ancient water body.",
    restoration: "Active restoration under the Koramangala Valley project",
    lat: 12.9352, lng: 77.6245,
  },
  {
    name: "Hessarghatta Reservoir",
    kannada: "ಹೇಸರಘಟ್ಟ ಜಲಾಶಯ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/BangaloreLake.jpg/1280px-BangaloreLake.jpg",
    area: "3,000 acres",
    fact: "Built in 1894 as Bangalore's first water supply reservoir. The surrounding grasslands are now a rare open habitat for blackbuck and wolves.",
    restoration: "Protected as a grassland reserve: one of Karnataka's most important open ecosystems",
    lat: 13.1285, lng: 77.4761,
  },
  {
    name: "Hulimavu Lake",
    kannada: "ಹುಲಿಮಾವು ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg/1280px-Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg",
    area: "65 acres",
    fact: "A restored gem in South Bangalore surrounded by BTM Layout and Begur. Its walking path sees thousands of residents every morning.",
    restoration: "Citizen trust restored it from an encroached wasteland into a thriving bird habitat",
    lat: 12.8850, lng: 77.6128,
  },
  {
    name: "Doddanekundi Lake",
    kannada: "ದೊಡ್ಡನೆಕ್ಕುಂದಿ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Kaikondanahalli_Lake_Bangalore.jpg/1280px-Kaikondanahalli_Lake_Bangalore.jpg",
    area: "110 acres",
    fact: "A large lake straddling Whitefield and Marathahalli, once famous for its flamingos. A critical wetland fighting for survival amid rapid development.",
    restoration: "Ongoing advocacy by Whitefield Rising and BBMP to protect its catchment area",
    lat: 12.9631, lng: 77.7005,
  },
  {
    name: "Kaggadasapura Lake",
    kannada: "ಕಗ್ಗದಾಸಾಪುರ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Birds_at_Madiwala_Lake.jpg/1280px-Birds_at_Madiwala_Lake.jpg",
    area: "90 acres",
    fact: "A scenic lake near CV Raman Nagar, East Bangalore. Its restored bund and walking path are a beloved evening haunt for residents of the area.",
    restoration: "BBMP restoration with bund reinforcement and landscaping completed in 2019",
    lat: 12.9901, lng: 77.6640,
  },
  {
    name: "Lottegollahalli Lake",
    kannada: "ಲೊಟ್ಟೆಗೊಳ್ಳಹಳ್ಳಿ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sankey_Tank.jpg/1280px-Sankey_Tank.jpg",
    area: "55 acres",
    fact: "A quiet North Bangalore lake near Jalahalli, often missed by maps. One of the city's underrated birdwatching spots — grey herons and kingfishers are regulars.",
    restoration: "Community groups have kept encroachment at bay for over a decade",
    lat: 13.0298, lng: 77.5436,
  },
  {
    name: "Kommaghatta Lake",
    kannada: "ಕೊಮ್ಮಘಟ್ಟ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg/1280px-Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg",
    area: "80 acres",
    fact: "A large West Bangalore lake near Kengeri that few people outside the neighbourhood know about. Surrounded by rocky outcrops, it has a wild, unhurried beauty.",
    restoration: "Included in BBMP's lake rejuvenation list; awaiting full restoration",
    lat: 12.9087, lng: 77.4903,
  },
  {
    name: "Munnekolala Lake",
    kannada: "ಮುನ್ನೇಕೊಳಾಲ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Kaikondanahalli_Lake_Bangalore.jpg/1280px-Kaikondanahalli_Lake_Bangalore.jpg",
    area: "48 acres",
    fact: "A compact lake near Marathahalli surrounded by tech parks. Spot-billed ducks and cormorants turn up regularly, unbothered by the glass towers nearby.",
    restoration: "Restored by BBMP in 2018 with a walking path and native plantings",
    lat: 12.9541, lng: 77.7008,
  },
  {
    name: "Byrasandra Lake",
    kannada: "ಬೈರಸಂದ್ರ ಕೆರೆ",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Birds_at_Madiwala_Lake.jpg/1280px-Birds_at_Madiwala_Lake.jpg",
    area: "42 acres",
    fact: "Tucked inside CV Raman Nagar, this restored lake is a peaceful retreat steps from one of Bangalore's busiest corridors.",
    restoration: "Citizen-led effort restored it from an encroached plot to a landscaped park with a walking trail",
    lat: 12.9536, lng: 77.6382,
  },
];
