export interface BengaluruBird {
  name: string;
  kannada: string;
  scientific: string;
  taxonId: number;
  whereSeen: string;
  fact: string;
}

export const BANGALORE_BIRDS: BengaluruBird[] = [
  {
    name: "Purple Sunbird",
    kannada: "ನೇರಳೆ ಸೂರಕ್ಕಿ",
    scientific: "Cinnyris asiaticus",
    taxonId: 145193,
    whereSeen: "Flowering trees and gardens across Bengaluru — Cubbon Park and Lalbagh — hovering at blooms to feed on nectar.",
    fact: "The male is iridescent black-purple in breeding plumage but moults into dull yellow-olive in the off-season, looking like a completely different species.",
  },
  {
    name: "Rose-ringed Parakeet",
    kannada: "ಗುಲಾಬಿ ಕೊರಳಿನ ಗಿಳಿ",
    scientific: "Psittacula krameri",
    taxonId: 18911,
    whereSeen: "Abundant throughout Bengaluru in parks, gardens, and residential areas. Large roosts gather at Lalbagh and around the city's old rain trees.",
    fact: "One of the world's most successful introduced bird species — escaped cage birds have established feral populations across Europe, the Middle East, and East Asia.",
  },
  {
    name: "Indian Robin",
    kannada: "ಚಿಟ್ಟು ಮಡಿವಾಳ",
    scientific: "Copsychus fulicatus",
    taxonId: 145031,
    whereSeen: "Open rocky ground, roadsides, and scrubby edges around Hesaraghatta and the city's drier outskirts. Spotted hopping with tail cocked upright.",
    fact: "Only the male has the distinctive chestnut vent under the cocked tail. The female is plain brown and easily overlooked, yet pairs stay on the same territory year-round.",
  },
  {
    name: "Oriental Magpie-Robin",
    kannada: "ಮಡಿವಾಳ",
    scientific: "Copsychus saularis",
    taxonId: 204491,
    whereSeen: "One of Bengaluru's most familiar garden birds, found in any park or tree-lined street. The male sings loudly from prominent perches at dawn.",
    fact: "Bangladesh's national bird, celebrated for one of the most varied and melodious songs of any South Asian garden bird.",
  },
  {
    name: "Coppersmith Barbet",
    kannada: "ಕಂಚುಕುಟಿಗ",
    scientific: "Psilopogon haemacephalus",
    taxonId: 367521,
    whereSeen: "A year-round resident in Bengaluru's gardens and parks. Easiest to find by its monotonous, metronomic 'tuk-tuk-tuk' call from the dense canopy.",
    fact: "The Coppersmith Barbet excavates its own nest hole in dead or soft wood using only its beak, and the same pair often reuses the cavity for several consecutive seasons.",
  },
  {
    name: "Asian Koel",
    kannada: "ಕೋಗಿಲೆ",
    scientific: "Eudynamys scolopaceus",
    taxonId: 204510,
    whereSeen: "Heard throughout Bengaluru's parks and suburbs, especially before the monsoon. The loud, ascending whistle is a signature sound of the city's mornings.",
    fact: "The Asian Koel is a brood parasite that lays its eggs almost exclusively in House Crow nests. Unlike many cuckoos, the koel chick doesn't eject the host eggs — it just outcompetes them.",
  },
  {
    name: "Red-vented Bulbul",
    kannada: "ಪಿಕಳಾರ",
    scientific: "Pycnonotus cafer",
    taxonId: 14593,
    whereSeen: "Ubiquitous in every garden, park, and roadside thicket across Bengaluru. Often the first bird to call at dawn and one of the last to roost.",
    fact: "Red-vented Bulbuls are aggressive nest defenders — they'll mob much larger birds including crows and kites — and have been recorded eating over 40 plant species' fruits.",
  },
  {
    name: "House Sparrow",
    kannada: "ಗುಬ್ಬಚ್ಚಿ",
    scientific: "Passer domesticus",
    taxonId: 13858,
    whereSeen: "Wherever humans live in Bengaluru — nesting under roof tiles, in crevices of old buildings, and foraging around restaurants and market areas.",
    fact: "House Sparrow populations have declined sharply in urban India. Modern buildings offer fewer nesting crevices, and reduced insect populations leave chicks without enough protein to survive.",
  },
  {
    name: "Rock Pigeon",
    kannada: "ಪಾರಿವಾಳ",
    scientific: "Columba livia",
    taxonId: 3017,
    whereSeen: "Omnipresent on building ledges, flyovers, temples, and railway stations throughout Bengaluru. Flocks wheel over older parts of the city in the evenings.",
    fact: "Rock Pigeons were the first birds domesticated by humans — over 10,000 years ago. Every domestic and feral pigeon worldwide descends from wild cliff-nesting birds of South Asia.",
  },
  {
    name: "Little Egret",
    kannada: "ಸಣ್ಣ ಬೆಳ್ಳಕ್ಕಿ",
    scientific: "Egretta garzetta",
    taxonId: 4943,
    whereSeen: "Common at Bengaluru's urban lakes — Sankey Tank, Ulsoor Lake, Bellandur — wading in the shallows or perched on rocks with wings spread to dry.",
    fact: "Little Egrets were hunted almost to extinction in the 19th century for their delicate breeding plumes used in hats. International protection starting in the 1900s helped the species fully recover.",
  },
  {
    name: "Grey Heron",
    kannada: "ಬೂದು ಬಕ",
    scientific: "Ardea cinerea",
    taxonId: 4954,
    whereSeen: "A patient, solitary sentinel at Bengaluru's lakes and waterlogged areas, standing motionless for long periods before striking at fish.",
    fact: "Grey Herons have specially adapted neck vertebrae that let them retract into an S-shape for a powerful, lightning-fast strike — reaching speeds of over 30 km/h.",
  },
  {
    name: "Indian Pond Heron",
    kannada: "ಕೊಳದ ಬಕ",
    scientific: "Ardeola grayii",
    taxonId: 4993,
    whereSeen: "Extremely common at every pond, drain, and damp patch across Bengaluru. Masterfully cryptic when crouching still, but stunning white when it takes flight.",
    fact: "The Indian Pond Heron is so well-camouflaged crouching that people often nearly step on one before it explodes into flight, revealing brilliant white wings that seem to appear from nowhere.",
  },
  {
    name: "Brahminy Kite",
    kannada: "ಬಿಳಿ ಗರುಡ",
    scientific: "Haliastur indus",
    taxonId: 5406,
    whereSeen: "Regularly soaring over Bengaluru's lakes and open areas. Often spotted pirating food from other birds around Ulsoor Lake and Sankey Tank.",
    fact: "The Brahminy Kite is sacred in Hinduism as the vahana (vehicle) of Lord Vishnu. Its distinctive chestnut-and-white plumage makes it one of India's most recognisable raptors.",
  },
  {
    name: "Black Kite",
    kannada: "ಹದ್ದು",
    scientific: "Milvus migrans",
    taxonId: 5268,
    whereSeen: "The sky above Bengaluru's busy markets, waste areas, and the outer ring road is frequently filled with wheeling Black Kites scanning for scraps below.",
    fact: "Black Kites are uniquely adapted to urban scavenging. Studies show they can recognise and avoid individual humans who have previously disturbed them.",
  },
  {
    name: "White-throated Kingfisher",
    kannada: "ಮಿಂಚುಳ್ಳಿ",
    scientific: "Halcyon smyrnensis",
    taxonId: 204519,
    whereSeen: "Bengaluru's most visible kingfisher — often perched on telephone wires and garden walls far from water, hunting lizards and large insects.",
    fact: "Unlike most kingfishers, this species doesn't need to live near water. It eats insects, earthworms, small snakes, and frogs, making it perfectly suited to dry urban habitats.",
  },
  {
    name: "Common Kingfisher",
    kannada: "ನೀಲಿ ಮಿಂಚುಳ್ಳಿ",
    scientific: "Alcedo atthis",
    taxonId: 2599,
    whereSeen: "Along the vegetated banks of Bengaluru's cleaner lakes and streams. Easier to hear its sharp whistle than to spot its jewel-like colours in the reeds.",
    fact: "The Common Kingfisher dives at up to 40 km/h. Its bill is so precisely angled that it corrects for water refraction without any conscious adjustment — a system engineers have applied to bullet-train design.",
  },
  {
    name: "Indian Peafowl",
    kannada: "ನವಿಲು",
    scientific: "Pavo cristatus",
    taxonId: 1204,
    whereSeen: "More common than expected on Bengaluru's residential periphery and green campuses like GKVK and IISc. Small groups also wander into Lalbagh in the early morning.",
    fact: "The peacock's magnificent 'tail' is actually its upper tail covert feathers, not the true tail. Each eye feather is grown fresh every year after the monsoon moult.",
  },
  {
    name: "Common Myna",
    kannada: "ಗೊರವಂಕ",
    scientific: "Acridotheres tristis",
    taxonId: 204454,
    whereSeen: "Among the most abundant birds in Bengaluru, found on every street, park, and open ground — often foraging alongside pedestrians for scraps.",
    fact: "The Common Myna was listed by the IUCN as one of the world's 100 worst invasive species, due to its aggressive competition with native birds for nest cavities across Australia and the Pacific.",
  },
  {
    name: "Jungle Myna",
    kannada: "ಕಾಡು ಗೊರವಂಕ",
    scientific: "Acridotheres fuscus",
    taxonId: 14869,
    whereSeen: "Often found alongside Common Mynas in Bengaluru's parks and semi-open areas. Distinguished by its tuft of feathers at the bill base and orange eye patch.",
    fact: "Jungle Mynas form mixed-species feeding flocks with Common Mynas but maintain a distinct pecking order. Practiced birders learn to separate the two by their subtly different nasal calls.",
  },
  {
    name: "Spotted Dove",
    kannada: "ಚೋರೆಹಕ್ಕಿ",
    scientific: "Spilopelia chinensis",
    taxonId: 144549,
    whereSeen: "A familiar dove of Bengaluru's parks, gardens, and rooftops, often seen walking on the ground in pairs and producing its soft, rolling coo.",
    fact: "The Spotted Dove's distinctive black-and-white chequered neck patch is absent in juveniles and develops fully only after the first moult.",
  },
  {
    name: "Laughing Dove",
    kannada: "ಕಂದು ಬೆಳವ",
    scientific: "Spilopelia senegalensis",
    taxonId: 1455922,
    whereSeen: "Common in Bengaluru's drier open areas, terraces, and garden edges, usually seen in pairs. Its bubbling call is a gentle background sound in older neighbourhoods.",
    fact: "The Laughing Dove takes its name from its rolling, chuckling call. It's one of the few dove species that doesn't need free-standing water, obtaining moisture from seeds and green food.",
  },
  {
    name: "Yellow-billed Babbler",
    kannada: "ಹಳದಿ ಕೊಕ್ಕಿನ ಹರಟೆಮಲ್ಲ",
    scientific: "Argya affinis",
    taxonId: 1289422,
    whereSeen: "Highly social flocks of six to ten birds are a common sight in Bengaluru's parks and scrub edges, noisily foraging through leaf litter together.",
    fact: "Yellow-billed Babblers are cooperative breeders — multiple adults in the flock help raise a single pair's chicks, a behaviour known as alloparenting that's relatively rare among passerines.",
  },
  {
    name: "Jungle Babbler",
    kannada: "ಕಾಡು ಹರಟೆಮಲ್ಲ",
    scientific: "Argya striata",
    taxonId: 1289423,
    whereSeen: "Noisy parties of seven or eight birds — giving rise to the folk name 'Seven Sisters' — forage through undergrowth in Cubbon Park and Lalbagh throughout the year.",
    fact: "Jungle Babblers are highly territorial and the entire flock defends the territory cooperatively. They have a rich vocabulary of calls for alarm, contact, and group coordination.",
  },
  {
    name: "Indian Silverbill",
    kannada: "ಬೆಳ್ಳಿ ಕೊಕ್ಕಿನ ರಾಟವಾಳ",
    scientific: "Euodice malabarica",
    taxonId: 145350,
    whereSeen: "Found in dry open scrub and grassland on Bengaluru's outskirts, particularly around Hesaraghatta and Turahalli. Moves in fast-flying compact flocks.",
    fact: "Indian Silverbills weave old nests into domed roosting balls where the entire flock sleeps together at night — reducing heat loss and guarding against predators simultaneously.",
  },
  {
    name: "Baya Weaver",
    kannada: "ನೇಯ್ಗಾರ ಪಕ್ಷಿ",
    scientific: "Ploceus philippinus",
    taxonId: 13794,
    whereSeen: "Colonial nesting flocks at marshy edges of lakes like Hebbal and Bellandur. Males weave characteristic flask-shaped hanging nests from palm and grass strips.",
    fact: "A male Baya Weaver builds multiple incomplete nests simultaneously to attract females. If a female rejects one, he dismantles it entirely and starts again.",
  },
  {
    name: "Black Drongo",
    kannada: "ಕಾಜಾಣ",
    scientific: "Dicrurus macrocercus",
    taxonId: 8277,
    whereSeen: "A bold, fork-tailed silhouette on roadside wires and fence posts across Bengaluru's open areas. Often seen dive-bombing much larger raptors that stray near its nest.",
    fact: "Black Drongos use false alarm calls to scare other birds away from food, then steal it — a form of deceptive vocal mimicry documented in scientific studies.",
  },
  {
    name: "White-breasted Waterhen",
    kannada: "ಹುಂಡುಕೋಳಿ",
    scientific: "Amaurornis phoenicurus",
    taxonId: 199,
    whereSeen: "Skulking along reed-fringed shores at Sankey Tank, Ulsoor Lake, and Hesaraghatta Reservoir. Often heard before seen — its loud, cackling calls start at dusk.",
    fact: "White-breasted Waterhens are surprisingly accomplished climbers, ascending reed stems and low shrubs to escape danger, contrary to the typical ground-hugging behaviour of rails.",
  },
  {
    name: "Grey-headed Swamphen",
    kannada: "ಕೆನ್ನೀಲಿ ನೀರು ಕೋಳಿ",
    scientific: "Porphyrio poliocephalus",
    taxonId: 474332,
    whereSeen: "Resident at Bengaluru's larger wetlands including Hebbal Lake and Madiwala Lake, striding through floating vegetation with its oversized feet.",
    fact: "The Grey-headed Swamphen uses its enormous feet to hold food down while eating — picking up a reed stem and manipulating it with one foot like a hand, a behaviour uncommon among birds.",
  },
  {
    name: "Greater Flameback",
    kannada: "ದೊಡ್ಡ ಹೊಂಬೆನ್ನಿನ ಮರಕುಟಿಗ",
    scientific: "Chrysocolaptes guttacristatus",
    taxonId: 201081,
    whereSeen: "In well-wooded parts of Bengaluru including Cubbon Park and the IISc campus. Its loud, rattling call often draws attention before the bird is spotted.",
    fact: "The Greater Flameback can hammer up to 20 times per second. Its skull has specialised spongy bone and a hyoid bone that wraps around the skull to absorb each impact.",
  },
  {
    name: "Black-rumped Flameback",
    kannada: "ಹೊಂಬೆನ್ನಿನ ಮರಕುಟಿಗ",
    scientific: "Dinopium benghalense",
    taxonId: 979697,
    whereSeen: "The most commonly seen woodpecker in Bengaluru's urban parks and gardens, including Lalbagh and Cubbon Park. Often spotted spiralling up the trunk of large rain trees.",
    fact: "Unlike most woodpeckers, this species regularly forages on the ground, probing ant and termite mounds — making it one of the few woodpeckers adapted to both arboreal and terrestrial feeding.",
  },
];
