export interface Startup {
  name: string;
  founded: number;
  founder: string;
  description: string;
  funFact: string;
  category: string;
  color: string;
}

export const BANGALORE_STARTUPS: Startup[] = [
  {
    name: "Infosys",
    founded: 1981,
    founder: "N.R. Narayana Murthy & 6 co-founders",
    description: "The company that put Indian IT on the global map. Started with $250 and a dream.",
    funFact: "Started with a capital of $250 borrowed from the founders' wives",
    category: "IT Services",
    color: "#0061A0",
  },
  {
    name: "Wipro",
    founded: 1945,
    founder: "M.H. Hasham Premji",
    description: "From vegetable oil to global tech giant: one of the world's great reinvention stories",
    funFact: "Started as Western India Vegetable Products. Pivoted to tech under Azim Premji.",
    category: "IT Services",
    color: "#341557",
  },
  {
    name: "Flipkart",
    founded: 2007,
    founder: "Sachin Bansal & Binny Bansal",
    description: "The e-commerce revolution that made India shop online: from books to everything",
    funFact: "First order was a book: 'Leaving Microsoft to Change the World'. Poetic.",
    category: "E-commerce",
    color: "#F74F00",
  },
  {
    name: "Swiggy",
    founded: 2014,
    founder: "Sriharsha Majety, Nandan Reddy, Rahul Jaimini",
    description: "Brought restaurant food to your door in 30 minutes. Transformed urban eating habits.",
    funFact: "Started with 6 delivery partners and 25 restaurant partners in Koramangala",
    category: "Food Tech",
    color: "#FC8019",
  },
  {
    name: "Ola",
    founded: 2010,
    founder: "Bhavish Aggarwal & Ankit Bhati",
    description: "Reinvented how India travels: from ride-hailing to electric vehicles",
    funFact: "Bhavish started Ola after being stranded due to an unprofessional cab driver",
    category: "Mobility",
    color: "#5CB85C",
  },
  {
    name: "Razorpay",
    founded: 2014,
    founder: "Harshil Mathur & Shashank Kumar",
    description: "The payments infrastructure powering India's digital economy",
    funFact: "Rejected by YC initially. Got in on reapplication and became one of India's most valuable fintech companies.",
    category: "Fintech",
    color: "#2D80F2",
  },
  {
    name: "Meesho",
    founded: 2015,
    founder: "Vidit Aatrey & Sanjeev Barnwal",
    description: "Empowering millions of micro-entrepreneurs to sell online: social commerce for India",
    funFact: "Enables housewives and small sellers to run businesses with zero investment",
    category: "Social Commerce",
    color: "#9B2D9C",
  },
  {
    name: "Unacademy",
    founded: 2015,
    founder: "Gaurav Munjal, Roman Saini, Hemesh Singh",
    description: "Making quality education accessible to every Indian student",
    funFact: "Co-founder Roman Saini left a medical career at AIIMS to build this",
    category: "EdTech",
    color: "#0C3547",
  },
  {
    name: "Zepto",
    founded: 2021,
    founder: "Aadit Palicha & Kaivalya Vohra",
    description: "10-minute grocery delivery, built by two 19-year-old Stanford dropouts",
    funFact: "Both founders dropped out of Stanford to build Zepto in Bengaluru",
    category: "Quick Commerce",
    color: "#7C3AED",
  },
  {
    name: "BYJU'S",
    founded: 2011,
    founder: "Byju Raveendran",
    description: "The learning app that made education engaging for 150 million students",
    funFact: "Byju started by teaching friends in a stadium. 1200 students showed up.",
    category: "EdTech",
    color: "#222222",
  },
  {
    name: "Cure.fit",
    founded: 2016,
    founder: "Mukesh Bansal & Ankit Nagori",
    description: "Making fitness, health food, and mental wellness accessible to all",
    funFact: "Launched with the vision that wellness should be like ordering coffee: simple and everyday",
    category: "Health & Fitness",
    color: "#E81C4F",
  },
  {
    name: "Dunzo",
    founded: 2014,
    founder: "Kabeer Biswas",
    description: "The hyperlocal delivery pioneer: anything, from anywhere, delivered fast",
    funFact: "Started as a WhatsApp group where Kabeer personally ran errands for people",
    category: "Logistics",
    color: "#00C9A7",
  },
  {
    name: "Namma Yatri",
    founded: 2022,
    founder: "Juspay (Bengaluru fintech)",
    description: "Open-source, zero-commission auto-rickshaw app built for drivers by Bangaloreans",
    funFact: "Drivers keep 100% of fares. No platform commission. True public good technology.",
    category: "Mobility",
    color: "#2D5016",
  },
  {
    name: "Browserstack",
    founded: 2011,
    founder: "Ritesh Arora & Nakul Aggarwal",
    description: "The tool every web developer uses: cross-browser testing from Bengaluru to the world",
    funFact: "Used by Microsoft, Twitter, and 50,000+ companies globally",
    category: "Developer Tools",
    color: "#FF6C37",
  },
  {
    name: "Chargebee",
    founded: 2011,
    founder: "Krish Subramanian & Rajaraman Santhanam",
    description: "Subscription billing infrastructure powering thousands of SaaS companies globally",
    funFact: "Bootstrapped for 7 years before raising. Proving patient capital builds lasting companies.",
    category: "Fintech/SaaS",
    color: "#FF6B35",
  },
  {
    name: "Postman",
    founded: 2014,
    founder: "Abhinav Asthana, Abhijit Kane, Ankit Sobti",
    description: "The API platform used by 30 million developers worldwide, built in Bengaluru",
    funFact: "Started as a Chrome extension that Abhinav built to solve his own API testing frustration",
    category: "Developer Tools",
    color: "#EF5B25",
  },
  {
    name: "Cred",
    founded: 2018,
    founder: "Kunal Shah",
    description: "Making credit card management rewarding and building India's most premium fintech",
    funFact: "Kunal's previous startup FreeCharge was acquired for $400M. He immediately started again.",
    category: "Fintech",
    color: "#1A1A2E",
  },
  {
    name: "PhonePe",
    founded: 2015,
    founder: "Sameer Nigam, Rahul Chari, Burzin Engineer",
    description: "India's largest UPI payments platform: 500 million registered users",
    funFact: "Separated from Walmart/Flipkart and moved HQ back to Bengaluru in a landmark move",
    category: "Fintech",
    color: "#5F259F",
  },
  {
    name: "InMobi",
    founded: 2007,
    founder: "Naveen Tewari",
    description: "India's first mobile advertising unicorn: pioneering mobile marketing globally",
    funFact: "One of the first Indian companies to achieve unicorn status, without US listing",
    category: "AdTech",
    color: "#E74C3C",
  },
  {
    name: "Honasa Consumer (Mamaearth)",
    founded: 2016,
    founder: "Varun Alagh & Ghazal Alagh",
    description: "Natural, toxin-free personal care built with a mother's love for her baby",
    funFact: "Started because Ghazal couldn't find safe products for her newborn son",
    category: "Consumer",
    color: "#4CAF50",
  },
  {
    name: "Groww",
    founded: 2016,
    founder: "Lalit Keshre, Harsh Jain, Neeraj Singh, Ishan Bansal",
    description: "Made stock market investing simple enough for first-time investors across India",
    funFact: "Crossed 50 million users faster than any other Indian investment platform. Built in Bengaluru, trusted by Bharat.",
    category: "Fintech",
    color: "#00D09C",
  },
  {
    name: "Smallcase",
    founded: 2015,
    founder: "Vasanth Kamath, Anugrah Khan, Rohan Gupta",
    description: "Reinvented how Indians invest in stocks: thematic baskets built by professional researchers",
    funFact: "Started at an IIIT Bangalore hackathon. Now manages portfolios worth thousands of crores for retail investors.",
    category: "Fintech",
    color: "#2B65EC",
  },
  {
    name: "Practo",
    founded: 2008,
    founder: "Shashank ND & Abhinav Lal",
    description: "India's largest digital health platform: doctor discovery, consultations, and health records in one place",
    funFact: "Started with two IIT Kharagpur graduates who couldn't find a doctor's phone number. Now serves 100 million patients.",
    category: "HealthTech",
    color: "#5CB8E4",
  },
  {
    name: "Urban Company",
    founded: 2014,
    founder: "Abhiraj Singh Bhal, Varun Khaitan, Raghav Chandra",
    description: "Transformed home services into a professional, tech-driven experience across India and the world",
    funFact: "Rebranded from UrbanClap to Urban Company in 2020. Now operates in 35 cities across 4 countries.",
    category: "Home Services",
    color: "#7C4DFF",
  },
  {
    name: "Rapido",
    founded: 2015,
    founder: "Aravind Sanka, Rishikesh SR, Pavan Guntupalli",
    description: "India's largest bike taxi platform: the fastest, cheapest way to beat Bangalore traffic",
    funFact: "Three IIT graduates built it after personally experiencing Bangalore's impossible traffic. Now in 100+ cities.",
    category: "Mobility",
    color: "#FFD700",
  },
  {
    name: "Acko Insurance",
    founded: 2016,
    founder: "Varun Dua",
    description: "India's first digital-native insurance company: buy a policy in minutes, claim in hours",
    funFact: "India's youngest insurance unicorn. Partnered with Amazon India to distribute car insurance at checkout.",
    category: "Insurtech",
    color: "#FF6B6B",
  },
  {
    name: "Darwinbox",
    founded: 2015,
    founder: "Rohit Chennamaneni, Chaitanya Peddi, Jayant Paleti",
    description: "Modern HR software built for Asian enterprises: the Workday of the East",
    funFact: "Used by Swiggy, Paytm, and over 850 enterprises across 90+ countries. Valued at over a billion dollars.",
    category: "HR Tech",
    color: "#F97316",
  },
  {
    name: "ClearTax",
    founded: 2011,
    founder: "Archit Gupta",
    description: "Made filing income tax returns simple for millions of Indians who found it baffling",
    funFact: "Archit started it after watching his father struggle with a paper tax return in San Francisco. Now files returns for 6 million people.",
    category: "Fintech",
    color: "#3B82F6",
  },
  {
    name: "Simplilearn",
    founded: 2009,
    founder: "Krishna Kumar",
    description: "World's largest professional certification platform: upskilling India and the world for the digital economy",
    funFact: "Started as a blog about project management certifications. Now has 40 lakh learners in 150 countries.",
    category: "EdTech",
    color: "#1E293B",
  },
  {
    name: "Juspay",
    founded: 2012,
    founder: "Vimal Kumar & Ramanathan RV",
    description: "The invisible payments infrastructure that powers Swiggy, Amazon, IRCTC, and half of India's digital transactions",
    funFact: "You've probably used Juspay dozens of times without knowing it. Processes 50 million transactions daily.",
    category: "Fintech",
    color: "#0EA5E9",
  },
  {
    name: "Perfios",
    founded: 2007,
    founder: "V.R. Govindarajan & Debasish Chakraborty",
    description: "Real-time financial data intelligence that powers credit decisions at India's biggest banks",
    funFact: "The quiet giant of Indian fintech: most banks use Perfios for loan verification but almost no one has heard of it.",
    category: "Fintech",
    color: "#6366F1",
  },
];
