export interface Escape {
  name: string;
  kannada: string;
  distance: string;       // e.g. "60 km"
  driveTime: string;      // e.g. "1.5 hrs"
  region: string;         // e.g. "Northern Hills"
  bestSeason: string;     // e.g. "Oct – Feb"
  thingsToDo: string[];   // 3 bullet items
  tagline: string;
  fact: string;
  emoji: string;
  photo: string;          // Wikimedia Commons verified URL
}

export const BANGALORE_ESCAPES: Escape[] = [
  {
    name: "Nandi Hills",
    kannada: "ನಂದಿ ಬೆಟ್ಟ",
    distance: "60 km",
    driveTime: "1.5 hrs",
    region: "Northern Hills",
    bestSeason: "Oct – Feb",
    thingsToDo: ["Watch sunrise above the cloud sea", "Cycle the winding hill road", "Explore Tipu Sultan's fort"],
    tagline: "Bengaluru's favourite weekend alarm clock.",
    fact: "At 1,478 m above sea level, Tipu Sultan used this hill as his summer retreat. On clear mornings the cloud sea below makes it feel like you're standing on an island.",
    emoji: "🌄",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Sunrise_%40_Nandi_Hills%2C_Bangalore%2C_India.jpg/1280px-Sunrise_%40_Nandi_Hills%2C_Bangalore%2C_India.jpg",
  },
  {
    name: "Coorg",
    kannada: "ಕೊಡಗು",
    distance: "260 km",
    driveTime: "5 hrs",
    region: "Western Ghats",
    bestSeason: "Oct – Mar",
    thingsToDo: ["Walk through a coffee estate at dawn", "Rafting on the Barapole river", "Visit Abbey Falls"],
    tagline: "Scotland of India, but with better coffee.",
    fact: "Coorg produces about 30% of India's total coffee. The land is blanketed in Arabica and Robusta estates where you can walk between the rows before breakfast.",
    emoji: "☕",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Ripe_Seeds_Coffee_Robusta_Coorg_Karnataka_India_Feb24_D72_25688.jpg/1280px-Ripe_Seeds_Coffee_Robusta_Coorg_Karnataka_India_Feb24_D72_25688.jpg",
  },
  {
    name: "Shivanasamudra",
    kannada: "ಶಿವನಸಮುದ್ರ",
    distance: "135 km",
    driveTime: "2.5 hrs",
    region: "Mandya District",
    bestSeason: "Aug – Nov",
    thingsToDo: ["Watch the twin waterfalls at full monsoon force", "Coracle ride on the Cauvery", "Visit the 19th-century power station ruins"],
    tagline: "The waterfall that powers an entire city.",
    fact: "Shivanasamudra was home to Asia's first hydroelectric power station in 1902, built to send electricity all the way to Kolar Gold Fields. The falls are at their most spectacular during and just after monsoon.",
    emoji: "💧",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Shivanasamudra_Falls_%28August_2018%29_2.jpg/1280px-Shivanasamudra_Falls_%28August_2018%29_2.jpg",
  },
  {
    name: "Sakleshpur",
    kannada: "ಸಕಲೇಶಪುರ",
    distance: "220 km",
    driveTime: "4 hrs",
    region: "Hassan District",
    bestSeason: "Jul – Sep",
    thingsToDo: ["Trek the Bisle Reserve Forest", "Walk the ghost-haunted Donigal railway track", "Stay in a plantation bungalow"],
    tagline: "Misty mornings and old railway magic.",
    fact: "The defunct Donigal railway track through Sakleshpur was once considered an engineering marvel of British India. Trekkers now walk the abandoned line through 55 tunnels and 103 bridges.",
    emoji: "🌿",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Sakleshpur_%2C_Karnataka_%2C_India.jpg/1280px-Sakleshpur_%2C_Karnataka_%2C_India.jpg",
  },
  {
    name: "Mysuru",
    kannada: "ಮೈಸೂರು",
    distance: "145 km",
    driveTime: "3 hrs",
    region: "Southern Plains",
    bestSeason: "Sep – Nov (Dasara)",
    thingsToDo: ["Explore Mysore Palace at night (lit up at 7pm)", "Wander Devaraja Market", "Sunrise at Chamundi Hills"],
    tagline: "The City of Palaces needs no introduction.",
    fact: "Mysore Palace is India's second most visited monument after the Taj Mahal. During Dasara, 100,000 light bulbs illuminate it every night for 10 days.",
    emoji: "🏰",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Mysore_Palace_Morning.jpg/1280px-Mysore_Palace_Morning.jpg",
  },
  {
    name: "Kabini",
    kannada: "ಕಾಬಿನಿ",
    distance: "220 km",
    driveTime: "4 hrs",
    region: "Nagarhole",
    bestSeason: "Mar – Jun",
    thingsToDo: ["Evening jeep safari into Nagarhole", "Boat safari at sunrise", "Watch elephants cross the backwater"],
    tagline: "Where elephants outnumber tourists.",
    fact: "The Kabini backwaters at the Nagarhole National Park boundary is one of South India's finest wildlife corridors. In summer, elephants gather here in large herds as the only water source for miles.",
    emoji: "🐘",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Antarasante_Kabini_Backwaters.jpg/1280px-Antarasante_Kabini_Backwaters.jpg",
  },
  {
    name: "Ramanagara",
    kannada: "ರಾಮನಗರ",
    distance: "55 km",
    driveTime: "1 hr",
    region: "Southern Outskirts",
    bestSeason: "Oct – Mar",
    thingsToDo: ["Rock climbing on the silk worm boulders", "Spot vultures at Sholay Rock", "Cycle through silk villages"],
    tagline: "Sholay was filmed here. Vultures still live here.",
    fact: "Ramanagara's dramatic granite rocks are famous as the filming location for Sholay. The cliffs also host one of India's last viable colonies of Indian long-billed vultures.",
    emoji: "🧗",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Ramanagara_.jpg/1280px-Ramanagara_.jpg",
  },
  {
    name: "Skandagiri",
    kannada: "ಸ್ಕಂದಗಿರಿ",
    distance: "70 km",
    driveTime: "1.5 hrs",
    region: "Northern Hills",
    bestSeason: "Nov – Feb",
    thingsToDo: ["Night trek to the summit (3am start)", "Watch sunrise above the clouds", "Explore the ruined fort walls"],
    tagline: "A 3am alarm that actually feels worth it.",
    fact: "Skandagiri, also called Kalavara Durga, sits at 1,450 m. The night trek is a Bengaluru rite of passage, timed so trekkers reach the summit just as the sun rises above a sea of clouds.",
    emoji: "⛰️",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Skandagiri.jpg/1280px-Skandagiri.jpg",
  },
  {
    name: "BR Hills",
    kannada: "ಬಿ.ಆರ್. ಹಿಲ್ಸ್",
    distance: "210 km",
    driveTime: "4 hrs",
    region: "Biligirirangana Hills",
    bestSeason: "Oct – Mar",
    thingsToDo: ["Jeep safari through BRT Tiger Reserve", "Visit the Biligiri Ranganathaswamy Temple", "Bird watching at dawn"],
    tagline: "Where the Eastern Ghats meets the Western Ghats.",
    fact: "BR Hills is one of Karnataka's most biodiverse forest tracts, bridging two mountain ranges. It is home to one of the world's rarest indigenous communities, the Soligas, who have lived here for centuries.",
    emoji: "🌲",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Biligirirangan_Hills_View.jpg/1280px-Biligirirangan_Hills_View.jpg",
  },
  {
    name: "Anthargange",
    kannada: "ಅಂತರಗಂಗೆ",
    distance: "70 km",
    driveTime: "1.5 hrs",
    region: "Kolar District",
    bestSeason: "Oct – Feb",
    thingsToDo: ["Cave exploration in the volcanic rock caves", "Trek to the Gangadhareshwara temple summit", "Night camping on the plateau"],
    tagline: "Caves, boulders, and a spring that flows from rock.",
    fact: "Anthargange means 'underground Ganges' in Kannada. A natural spring flows from inside the volcanic rock cave complex at the summit of this hill, and the water is considered sacred.",
    emoji: "🕳️",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Antharagange.JPG/1280px-Antharagange.JPG",
  },
  {
    name: "Bheemeshwari",
    kannada: "ಭೀಮೇಶ್ವರಿ",
    distance: "100 km",
    driveTime: "2.5 hrs",
    region: "Mandya District",
    bestSeason: "Jun – Feb",
    thingsToDo: ["Mahseer fishing on the Cauvery", "Zipline and nature walks", "Kayaking on the backwaters"],
    tagline: "Bengaluru's river escape is closer than you think.",
    fact: "Bheemeshwari is a wildlife and nature camp on the banks of the Cauvery. The river here is famous for the mighty mahseer fish, which can grow to over 50 kg and is a protected species.",
    emoji: "🎣",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Cauvery_Kaveri_River_Karnataka_India_%285%29.jpg/1280px-Cauvery_Kaveri_River_Karnataka_India_%285%29.jpg",
  },
  {
    name: "Chikmagalur",
    kannada: "ಚಿಕ್ಕಮಗಳೂರು",
    distance: "245 km",
    driveTime: "5 hrs",
    region: "Western Ghats",
    bestSeason: "Oct – Mar",
    thingsToDo: ["Trek to Mullayanagiri — Karnataka's highest peak", "Walk through Baba Budangiri", "Visit a working coffee estate"],
    tagline: "Where Indian coffee was born.",
    fact: "Legend holds that the Sufi saint Baba Budan smuggled seven coffee beans from Yemen in the 17th century and planted them in these hills, starting India's coffee cultivation story.",
    emoji: "🏔️",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Mullayanagiri%2C_Chikmagalur_district_of_Karnataka.jpg/1280px-Mullayanagiri%2C_Chikmagalur_district_of_Karnataka.jpg",
  },
  {
    name: "Hampi",
    kannada: "ಹಂಪಿ",
    distance: "340 km",
    driveTime: "6 hrs",
    region: "Vijayanagara",
    bestSeason: "Oct – Feb",
    thingsToDo: ["Explore Virupaksha Temple and the bazaar ruins", "Sunrise over the boulder landscape", "Coracle across the Tungabhadra"],
    tagline: "A lost empire scattered across boulders.",
    fact: "Hampi was once the capital of the Vijayanagara Empire, one of the largest Hindu empires in history. At its peak in the 15th century it was reportedly the second-largest city in the world after Beijing.",
    emoji: "🏛️",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Hampi_-_Hemakuta_Hill%2C_Virupaksha_Temple.jpg/1280px-Hampi_-_Hemakuta_Hill%2C_Virupaksha_Temple.jpg",
  },
  {
    name: "Muthati",
    kannada: "ಮುತ್ತತ್ತಿ",
    distance: "115 km",
    driveTime: "2.5 hrs",
    region: "Kolar District",
    bestSeason: "Oct – Feb",
    thingsToDo: ["Nature trail through the forest reserve", "Cauvery riverbank walk", "Spot jungle fowl and hornbills"],
    tagline: "Bengaluru's quiet forest secret.",
    fact: "Muthati Wildlife Sanctuary on the Cauvery is one of Karnataka's least visited forest reserves, which means on most days you share the trails only with birds and the sound of the river.",
    emoji: "🌳",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Cauvery_Kaveri_River_Karnataka_India_%284%29.jpg/1280px-Cauvery_Kaveri_River_Karnataka_India_%284%29.jpg",
  },
  {
    name: "Horsley Hills",
    kannada: "ಹಾರ್ಸ್ಲಿ ಹಿಲ್ಸ್",
    distance: "150 km",
    driveTime: "3 hrs",
    region: "Andhra Border",
    bestSeason: "Oct – Mar",
    thingsToDo: ["Trek the Gali Banda viewpoint", "Visit the 100-year-old Eucalyptus trees", "Sunrise from Mallamma Peak"],
    tagline: "Cool, quiet, and completely underrated.",
    fact: "Horsley Hills was developed as a summer retreat by W.D. Horsley, a British collector, who built a bungalow here in the 1880s. The place still has a Eucalyptus tree he planted — over 150 years old and still standing.",
    emoji: "🌬️",
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Horsley_hills_HDR.jpg/1280px-Horsley_hills_HDR.jpg",
  },
];
