export interface Park {
  name: string;
  kannada: string;
  area: string;
  established: number;
  photo: string;
  fact: string;
  bestTime: string;
  lat: number;
  lng: number;
}

export const BANGALORE_PARKS: Park[] = [
  {
    name: "Cubbon Park",
    kannada: "ಕಬ್ಬನ್ ಪಾರ್ಕ್",
    area: "300 acres",
    established: 1870,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Cubbon_Park_W.jpg/1280px-Cubbon_Park_W.jpg",
    fact: "Home to 6,000 trees and over 68 species of plants. The city's green lungs and its favourite Sunday morning destination.",
    bestTime: "Early morning (6 to 8am): when walkers, joggers, and bird-watchers have it to themselves",
    lat: 12.9763, lng: 77.5929,
  },
  {
    name: "Lalbagh Botanical Garden",
    kannada: "ಲಾಲ್‌ಬಾಗ್ ಸಸ್ಯೋದ್ಯಾನ",
    area: "240 acres",
    established: 1760,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Glasshouse_and_fountain_at_lalbagh.jpg/1280px-Glasshouse_and_fountain_at_lalbagh.jpg",
    fact: "Founded by Hyder Ali in 1760. Contains a 3000 million year old rock formation and trees from around the world.",
    bestTime: "Republic Day and Independence Day: the flower show is legendary",
    lat: 12.9507, lng: 77.5843,
  },
  {
    name: "Bannerghatta Biological Park",
    kannada: "ಬನ್ನೇರುಘಟ್ಟ ಜೈವಿಕ ಉದ್ಯಾನ",
    area: "25,000 acres",
    established: 1971,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Lurking_tiger.jpg/1280px-Lurking_tiger.jpg",
    fact: "25,000 acres of protected forest just 22km from the city centre. Where tigers, elephants, and leopards roam.",
    bestTime: "Morning safari: the jungle is alive before 9am",
    lat: 12.7976, lng: 77.5784,
  },
  {
    name: "Nandi Hills",
    kannada: "ನಂದಿ ಬೆಟ್ಟ",
    area: "600+ acres",
    established: 1000,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Sunrise_%40_Nandi_Hills%2C_Bangalore%2C_India.jpg/1280px-Sunrise_%40_Nandi_Hills%2C_Bangalore%2C_India.jpg",
    fact: "60km from Bangalore at 1,478m. Tipu Sultan's summer retreat is now Bangalore's favourite weekend sunrise spot.",
    bestTime: "Sunrise: arrive by 5:30am for the cloud sea view",
    lat: 13.3702, lng: 77.6835,
  },
  {
    name: "Turahalli Forest",
    kannada: "ತುರಹಳ್ಳಿ ಕಾಡು",
    area: "644 acres",
    established: 1900,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Thurahalli%2C_Bengaluru%2C_Karnataka_560062%2C_India_-_panoramio_%282%29.jpg/1280px-Thurahalli%2C_Bengaluru%2C_Karnataka_560062%2C_India_-_panoramio_%282%29.jpg",
    fact: "The last surviving dry deciduous forest inside Bangalore's city limits. A hidden trail running sanctuary.",
    bestTime: "Early morning trail runs: peaceful, local, and gloriously green",
    lat: 12.8875, lng: 77.5484,
  },
  {
    name: "Bugle Rock Park",
    kannada: "ಬ್ಯೂಗಲ್ ರಾಕ್ ಪಾರ್ಕ್",
    area: "8 acres",
    established: 1927,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Bugle_Rock_Kahale.jpg/1280px-Bugle_Rock_Kahale.jpg",
    fact: "Built around a 3,000 million year old Archaean gneissic rock in Basavanagudi. One of Bangalore's oldest and most beloved neighbourhood parks.",
    bestTime: "Evening: the rock glows amber at sunset and the bats emerge at dusk",
    lat: 12.9408, lng: 77.5685,
  },
  {
    name: "Hesaraghatta Grasslands",
    kannada: "ಹೇಸರಘಟ್ಟ ಹುಲ್ಲುಗಾವಲು",
    area: "5,000+ acres",
    established: 1894,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/BangaloreLake.jpg/1280px-BangaloreLake.jpg",
    fact: "One of India's most important open grassland ecosystems just outside Bangalore. Home to the endangered Great Indian Bustard and wolves.",
    bestTime: "Winter mornings (November to February): the grasslands come alive with raptors and migratory birds",
    lat: 13.1285, lng: 77.4761,
  },
  {
    name: "Sankey Tank Garden",
    kannada: "ಸ್ಯಾಂಕಿ ಕೆರೆ ಉದ್ಯಾನ",
    area: "15 acres",
    established: 1882,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sankey_Tank.jpg/1280px-Sankey_Tank.jpg",
    fact: "The garden around Sankey Tank is one of Bangalore's most cherished morning spots. Joggers, yoga practitioners, and filter coffee walkers share it every dawn.",
    bestTime: "Early morning: the mist over the tank before 7am is ethereal",
    lat: 13.0107, lng: 77.5796,
  },
  {
    name: "Banashankari Temple Park",
    kannada: "ಬನಶಂಕರಿ ದೇವಸ್ಥಾನ ಉದ್ಯಾನ",
    area: "20 acres",
    established: 1915,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Cubbon_Park_W.jpg/1280px-Cubbon_Park_W.jpg",
    fact: "Surrounds the ancient Banashankari temple in South Bangalore. The temple tank, old trees, and quiet paths make it a sacred natural refuge in the city.",
    bestTime: "Early morning puja time: the fragrance of flowers and incense fills the air",
    lat: 12.9255, lng: 77.5468,
  },
  {
    name: "GKVK University Campus",
    kannada: "ಜಿ.ಕೆ.ವಿ.ಕೆ. ಆವರಣ",
    area: "1,400 acres",
    established: 1975,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Glasshouse_and_fountain_at_lalbagh.jpg/1280px-Glasshouse_and_fountain_at_lalbagh.jpg",
    fact: "The University of Agricultural Sciences campus is one of Bangalore's best-kept secrets: 1,400 acres of farms, orchards, research fields, and forest in the heart of North Bangalore.",
    bestTime: "Weekday mornings: the campus is open, peaceful, and gloriously green",
    lat: 13.0798, lng: 77.5798,
  },
  {
    name: "Jacaranda Avenue",
    kannada: "ಜಕಾರಂಡ ರಸ್ತೆ",
    area: "Tree-lined boulevard",
    established: 1930,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Cubbon_Park_W.jpg/1280px-Cubbon_Park_W.jpg",
    fact: "Bangalore's famous Jacaranda-lined roads — Bellary Road, MG Road, Cunningham Road — explode in violet-purple every March. The city is briefly another place entirely.",
    bestTime: "March to April: when the Jacaranda is in full bloom and the streets turn purple",
    lat: 12.9755, lng: 77.6080,
  },
  {
    name: "Whitefield Lake Park",
    kannada: "ವೈಟ್‌ಫೀಲ್ಡ್ ಕೆರೆ ಉದ್ಯಾನ",
    area: "30 acres",
    established: 2010,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg/1280px-Puttenahalli_Lake%2C_JP_Nagar%2C_Bangalore.jpg",
    fact: "A community park around the Whitefield lake that has become the green lung of East Bangalore's IT corridor. Proof that even the tech belt can have natural beauty.",
    bestTime: "Early morning before 8am: joggers, dog walkers, and quiet people enjoying the mist over the lake",
    lat: 12.9731, lng: 77.7494,
  },
  {
    name: "Kengeri Urban Forest",
    kannada: "ಕೆಂಗೇರಿ ನಗರ ಕಾಡು",
    area: "200 acres",
    established: 1985,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Thurahalli%2C_Bengaluru%2C_Karnataka_560062%2C_India_-_panoramio_%282%29.jpg/1280px-Thurahalli%2C_Bengaluru%2C_Karnataka_560062%2C_India_-_panoramio_%282%29.jpg",
    fact: "A quiet urban forest in West Bangalore that most residents don't know exists. Home to mongoose, porcupine, and over 80 bird species.",
    bestTime: "Weekday mornings: you may have the entire forest to yourself",
    lat: 12.9068, lng: 77.4836,
  },
];
