export interface FamousPerson {
  name: string;
  field: string;
  knownFor: string;
  quote: string;
  initials: string;
  color: string;
  era?: string;
}

export const FAMOUS_BANGALOREANS: FamousPerson[] = [
  {
    name: "Kiran Mazumdar-Shaw",
    field: "Biotech Pioneer",
    knownFor: "Founded Biocon: India's largest biotech company. Made insulin affordable for millions.",
    quote: "Innovation is the only way to beat competition.",
    initials: "KM",
    color: "#2D5016",
    era: "Contemporary",
  },
  {
    name: "N.R. Narayana Murthy",
    field: "IT Visionary",
    knownFor: "Co-founded Infosys with ₹10,000 borrowed from his wife. Built a global IT empire from a Bengaluru garage.",
    quote: "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong.",
    initials: "NM",
    color: "#0061A0",
    era: "Contemporary",
  },
  {
    name: "Sachin Bansal",
    field: "E-commerce Pioneer",
    knownFor: "Co-founded Flipkart at 25, sold it to Walmart for $16 billion: India's largest tech exit ever.",
    quote: "India is a country full of opportunities. We've only scratched the surface.",
    initials: "SB",
    color: "#C4560E",
    era: "Contemporary",
  },
  {
    name: "Girish Karnad",
    field: "Playwright & Actor",
    knownFor: "One of India's greatest playwrights: Tughlaq, Hayavadana, Naga-Mandala. Padma Bhushan laureate.",
    quote: "A play is not a piece of literature to be read, but a script for performance.",
    initials: "GK",
    color: "#7C3AED",
    era: "20th Century",
  },
  {
    name: "Prakash Padukone",
    field: "Badminton Legend",
    knownFor: "First Indian to win the All England Championship (1980): opened the door for Indian badminton.",
    quote: "Winning is not everything, but the effort to win is.",
    initials: "PP",
    color: "#C67C2A",
    era: "Contemporary",
  },
  {
    name: "C.V. Raman",
    field: "Nobel Laureate Physicist",
    knownFor: "Discovered the Raman Effect in Bengaluru (1928): India's first Nobel Prize in science.",
    quote: "Success can come to you by courageous devotion to the task lying in front of you.",
    initials: "CR",
    color: "#1D4ED8",
    era: "Early 20th Century",
  },
  {
    name: "U.R. Ananthamurthy",
    field: "Kannada Literature",
    knownFor: "Jnanpith Award-winning novelist: Samskara changed Kannada literature forever.",
    quote: "Literature is a way of seeing: it gives eyes to those who cannot see.",
    initials: "UA",
    color: "#5C3A1E",
    era: "20th Century",
  },
  {
    name: "Azim Premji",
    field: "Tech & Philanthropy",
    knownFor: "Built Wipro into a global tech company, then gave away ₹1 lakh crore to education causes.",
    quote: "The simplest questions are the most profound.",
    initials: "AP",
    color: "#6D28D9",
    era: "Contemporary",
  },
  {
    name: "Rahul Dravid",
    field: "Cricket Legend",
    knownFor: "'The Wall': trained at Bengaluru's cricket academy, represented Karnataka with pride for decades.",
    quote: "Hard work puts you where good luck can find you.",
    initials: "RD",
    color: "#1D6B2E",
    era: "Contemporary",
  },
  {
    name: "Kempe Gowda I",
    field: "Founder of Bengaluru",
    knownFor: "Built the first mud fort of Bengaluru in 1537: the city exists because of his extraordinary vision.",
    quote: "A city is the dream of its founder made real by the hands of its people.",
    initials: "KG",
    color: "#B45309",
    era: "16th Century",
  },
  {
    name: "Dr. Rajkumar",
    field: "Kannada Cinema Legend",
    knownFor: "The undisputed king of Kannada cinema. Acted in 200 films over five decades and became a symbol of Kannada identity and pride.",
    quote: "I am an actor and I will remain an actor. The rest is secondary.",
    initials: "DR",
    color: "#C67C2A",
    era: "20th Century",
  },
  {
    name: "Kuvempu",
    field: "Poet & Novelist",
    knownFor: "Karnataka's greatest poet, first Jnanpith Award winner from the state. Wrote 'Kuppali Venkatappa Puttappa', Karnataka's beloved state anthem.",
    quote: "Be a universal human being. Break all boundaries of caste, religion, and region.",
    initials: "KV",
    color: "#2D5016",
    era: "20th Century",
  },
  {
    name: "Anil Kumble",
    field: "Cricket Legend",
    knownFor: "India's greatest spin bowler. Took 619 Test wickets including the perfect ten in a single innings against Pakistan in Delhi.",
    quote: "The harder you work, the luckier you get.",
    initials: "AK",
    color: "#1D6B2E",
    era: "Contemporary",
  },
  {
    name: "Sudha Murthy",
    field: "Author & Philanthropist",
    knownFor: "Chairperson of Infosys Foundation and bestselling Kannada author. Has donated over ₹600 crore to education, healthcare, and rural development.",
    quote: "If you have money, use it for others. The joy you get from giving is far greater than what you receive.",
    initials: "SM",
    color: "#7C3AED",
    era: "Contemporary",
  },
  {
    name: "Puttanna Kanagal",
    field: "Kannada Film Director",
    knownFor: "The master of Kannada parallel cinema. Directed Sharapanjara and Nagara Haavu, films that redefined Indian regional cinema.",
    quote: "Cinema should reflect the truth of life, not escape from it.",
    initials: "PK",
    color: "#5C3A1E",
    era: "20th Century",
  },
  {
    name: "M. Visvesvaraya",
    field: "Engineer & Statesman",
    knownFor: "The greatest engineer India has produced. Designed the flood protection system for Hyderabad and the Krishna Raja Sagara dam. India celebrates Engineers' Day on his birthday.",
    quote: "Industry, hard work, and concentration of mind: these three are the secrets of success.",
    initials: "MV",
    color: "#0061A0",
    era: "Early 20th Century",
  },
  {
    name: "Gundappa Viswanath",
    field: "Cricket Legend",
    knownFor: "One of the most technically gifted batsmen in Indian cricket history. His square cut and off-side play made him beloved worldwide.",
    quote: "Cricket is a game that teaches you patience and humility.",
    initials: "GV",
    color: "#1D4ED8",
    era: "20th Century",
  },
];
