export interface KannadaWord {
  kannada: string;
  transliteration: string;
  meaning: string;
  example: { kannada: string; romanized: string; english: string };
  context: string;
  category?: string;
}

export const KANNADA_WORDS: KannadaWord[] = [
  {
    kannada: "ನಮಸ್ಕಾರ",
    transliteration: "Namaskāra",
    meaning: "Hello / Respectful greeting",
    example: { kannada: "ನಮಸ್ಕಾರ, ನೀವು ಹೇಗಿದ್ದೀರಿ?", romanized: "Namaskāra, nīvu hēgiddīri?", english: "Hello, how are you?" },
    context: "The universal Kannada greeting, used morning to night with folded hands",
    category: "everyday",
  },
  {
    kannada: "ಧನ್ಯವಾದ",
    transliteration: "Dhanyavāda",
    meaning: "Thank you",
    example: { kannada: "ನಿಮ್ಮ ಸಹಾಯಕ್ಕೆ ಧನ್ಯವಾದ", romanized: "Nimma sahāyakke dhanyavāda", english: "Thank you for your help" },
    context: "Directly translates to 'blessed words': gratitude with grace",
    category: "everyday",
  },
  {
    kannada: "ಸಕ್ಕತ್",
    transliteration: "Sakkat",
    meaning: "Awesome / Excellent (colloquial)",
    example: { kannada: "ಆ ಊಟ ಸಕ್ಕತ್ ಆಗಿತ್ತು!", romanized: "Ā ūṭa sakkat āgittu!", english: "That meal was absolutely awesome!" },
    context: "Pure Bangalore slang: you'll hear this everywhere from autos to boardrooms",
    category: "slang",
  },
  {
    kannada: "ಬಾ",
    transliteration: "Bā",
    meaning: "Come / Welcome",
    example: { kannada: "ನಮ್ಮ ಮನೆಗೆ ಬಾ", romanized: "Namma manege bā", english: "Come to our home" },
    context: "One of the warmest words in Kannada: an open, generous invitation",
    category: "everyday",
  },
  {
    kannada: "ಹೋಗೋಣ",
    transliteration: "Hōgōṇa",
    meaning: "Let's go",
    example: { kannada: "ಲಾಲ್‌ಬಾಗ್‌ಗೆ ಹೋಗೋಣ", romanized: "Lālbāggege hōgōṇa", english: "Let's go to Lalbagh" },
    context: "The Bangalorean's favourite call to adventure on a Sunday morning",
    category: "everyday",
  },
  {
    kannada: "ಚೆಲುವೆ",
    transliteration: "Cheluve",
    meaning: "Beautiful / Lovely",
    example: { kannada: "ಬೆಂಗಳೂರು ತುಂಬಾ ಚೆಲುವೆ", romanized: "Bengaḷūru tumbā cheluve", english: "Bangalore is very beautiful" },
    context: "Used for people, places, sunsets. Kannada has a poetic way with beauty.",
    category: "nature",
  },
  {
    kannada: "ಊಟ",
    transliteration: "Ūṭa",
    meaning: "Food / A proper meal",
    example: { kannada: "ಊಟ ಆಯ್ತಾ?", romanized: "Ūṭa āytā?", english: "Have you eaten? (used as a caring greeting)" },
    context: "Asking 'have you eaten?' is how Kannadigas say 'I care about you'",
    category: "food",
  },
  {
    kannada: "ಮಳೆ",
    transliteration: "Maḷe",
    meaning: "Rain",
    example: { kannada: "ಇಂದು ಮಳೆ ಬರುತ್ತೆ", romanized: "Indu maḷe barutte", english: "It will rain today" },
    context: "Bangalore's rain is legendary: celebrated, not cursed, by true locals",
    category: "nature",
  },
  {
    kannada: "ನೋಡು",
    transliteration: "Nōḍu",
    meaning: "Look / See / Observe",
    example: { kannada: "ಆ ಸೂರ್ಯಾಸ್ತ ನೋಡು!", romanized: "Ā sūryāsta nōḍu!", english: "Look at that sunset!" },
    context: "An invitation to pause and notice beauty: the Kannada way",
    category: "everyday",
  },
  {
    kannada: "ಹೊಸ",
    transliteration: "Hosa",
    meaning: "New / Fresh",
    example: { kannada: "ಹೊಸ ವರ್ಷದ ಶುಭಾಶಯಗಳು", romanized: "Hosa varṣada śubhāśayagaḷu", english: "Happy New Year" },
    context: "Bengaluru is always building something hosa: a perfect word for the city",
    category: "everyday",
  },
  {
    kannada: "ಸ್ವಾಗತ",
    transliteration: "Svāgata",
    meaning: "Welcome",
    example: { kannada: "ಬೆಂಗಳೂರಿಗೆ ಸ್ವಾಗತ", romanized: "Bengaḷūrige svāgata", english: "Welcome to Bengaluru" },
    context: "The city's spirit in one word: Bangalore has always welcomed the world",
    category: "everyday",
  },
  {
    kannada: "ರುಚಿ",
    transliteration: "Ruchi",
    meaning: "Taste / Flavour",
    example: { kannada: "ಈ ಕಾಫಿ ತುಂಬಾ ರುಚಿ", romanized: "Ī kāphi tumbā ruchi", english: "This coffee is very tasty" },
    context: "Filter coffee, dosa, bisibelebath: Bengaluru's ruchi is world-famous",
    category: "food",
  },
  {
    kannada: "ಆಕಾಶ",
    transliteration: "Ākāsha",
    meaning: "Sky",
    example: { kannada: "ಇಂದು ಆಕಾಶ ತುಂಬಾ ಸುಂದರ", romanized: "Indu ākāśa tumbā sundara", english: "The sky is very beautiful today" },
    context: "Bangalore's sky, especially post-rain, is genuinely breathtaking",
    category: "nature",
  },
  {
    kannada: "ಹಾಡು",
    transliteration: "Hāḍu",
    meaning: "Song",
    example: { kannada: "ಒಂದು ಹಾಡು ಹಾಡು", romanized: "Ondu hāḍu hāḍu", english: "Sing a song" },
    context: "Karnataka has a rich musical tradition: from Carnatic to Kannada film music",
    category: "culture",
  },
  {
    kannada: "ಗೆಳೆಯ",
    transliteration: "Geḷeya",
    meaning: "Friend",
    example: { kannada: "ನೀನು ನನ್ನ ಒಳ್ಳೆ ಗೆಳೆಯ", romanized: "Nīnu nanna oḷḷe geḷeya", english: "You are my good friend" },
    context: "Bangaloreans make friends for life: the city's warmth is real",
    category: "everyday",
  },
  {
    kannada: "ನಗು",
    transliteration: "Nagu",
    meaning: "Smile / Laughter",
    example: { kannada: "ನಿನ್ನ ನಗು ಚೆಂದ", romanized: "Ninna nagu chenda", english: "Your smile is lovely" },
    context: "The most beautiful thing in any language",
    category: "everyday",
  },
  {
    kannada: "ಬೆಳಕು",
    transliteration: "Beḷaku",
    meaning: "Light",
    example: { kannada: "ಬೆಳಗಿನ ಬೆಳಕು ಚೆಂದ", romanized: "Beḷagina beḷaku chenda", english: "Morning light is beautiful" },
    context: "Bengaluru's golden morning light through Cubbon Park trees: pure magic",
    category: "nature",
  },
  {
    kannada: "ಅನ್ನ",
    transliteration: "Anna",
    meaning: "Rice / Food (sacred)",
    example: { kannada: "ಅನ್ನ ದೇವರು", romanized: "Anna dēvaru", english: "Food is God" },
    context: "In Karnataka culture, wasting food is deeply frowned upon: food is sacred",
    category: "food",
  },
  {
    kannada: "ನಾಡು",
    transliteration: "Nāḍu",
    meaning: "Land / Homeland / Region",
    example: { kannada: "ಕನ್ನಡ ನಾಡು", romanized: "Kannaḍa nāḍu", english: "The Kannada homeland" },
    context: "Karnataka means 'elevated land': a place of deep pride and identity",
    category: "culture",
  },
  {
    kannada: "ಮನೆ",
    transliteration: "Mane",
    meaning: "Home / House",
    example: { kannada: "ಬೆಂಗಳೂರು ನನ್ನ ಮನೆ", romanized: "Bengaḷūru nanna mane", english: "Bengaluru is my home" },
    context: "Millions have moved here and made it mane: the city embraces everyone",
    category: "everyday",
  },
  {
    kannada: "ಶಾಂತಿ",
    transliteration: "Shānti",
    meaning: "Peace / Tranquility",
    example: { kannada: "ಕಬ್ಬನ್ ಪಾರ್ಕ್‌ನಲ್ಲಿ ಶಾಂತಿ ಇದೆ", romanized: "Kabban pārkinal·li śānti ide", english: "There is peace in Cubbon Park" },
    context: "Find your shanti in one of Bangalore's beautiful green spaces",
    category: "nature",
  },
  {
    kannada: "ಉತ್ಸಾಹ",
    transliteration: "Utsāha",
    meaning: "Enthusiasm / Energy",
    example: { kannada: "ಅವರಿಗೆ ತುಂಬಾ ಉತ್ಸಾಹ ಇದೆ", romanized: "Avarige tumbā utsāha ide", english: "They have a lot of enthusiasm" },
    context: "The energy of Bengaluru's startup scene, perfectly captured in one word",
    category: "culture",
  },
  {
    kannada: "ಕನಸು",
    transliteration: "Kanasu",
    meaning: "Dream",
    example: { kannada: "ದೊಡ್ಡ ಕನಸು ಕಾಣು", romanized: "Doḍḍa kanasu kāṇu", english: "Dream big" },
    context: "Millions come to Bengaluru chasing their kanasu. Many find it.",
    category: "culture",
  },
  {
    kannada: "ಒಲವು",
    transliteration: "Olavu",
    meaning: "Love / Affection",
    example: { kannada: "ಬೆಂಗಳೂರಿನ ಮೇಲೆ ನನಗೆ ಒಲವು", romanized: "Bengaḷūrina mēle nanage olavu", english: "I have love for Bengaluru" },
    context: "The word this portal was built from. Pure olavu for the city.",
    category: "everyday",
  },
  {
    kannada: "ಬಿಸಿಲು",
    transliteration: "Bisilu",
    meaning: "Sunshine / Warm sunlight",
    example: { kannada: "ಬೆಳಿಗ್ಗೆ ಬಿಸಿಲು ತುಂಬಾ ಚೆಂದ", romanized: "Beḷigge bisilu tumbā chenda", english: "The morning sunshine is so beautiful" },
    context: "Bengaluru's bisilu is gentle: not harsh. The city was literally designed for this kind of light.",
    category: "nature",
  },
  {
    kannada: "ಕಾಡು",
    transliteration: "Kāḍu",
    meaning: "Forest / Wilderness",
    example: { kannada: "ತುರಹಳ್ಳಿ ಕಾಡಿಗೆ ಹೋಗೋಣ", romanized: "Turahaḷḷi kāḍige hōgōṇa", english: "Let's go to Turahalli forest" },
    context: "Bengaluru is one of few cities with forest inside its limits: kāḍu lives in the city's soul",
    category: "nature",
  },
  {
    kannada: "ಹೂವು",
    transliteration: "Hūvu",
    meaning: "Flower",
    example: { kannada: "ಲಾಲ್‌ಬಾಗ್‌ನಲ್ಲಿ ಹೂವುಗಳು ಚೆಂದ", romanized: "Lālbāginal·li hūvugaḷu chenda", english: "The flowers in Lalbagh are beautiful" },
    context: "Lalbagh's flower shows are legendary: the city blooms twice a year",
    category: "nature",
  },
  {
    kannada: "ಮರ",
    transliteration: "Mara",
    meaning: "Tree",
    example: { kannada: "ಕಬ್ಬನ್ ಪಾರ್ಕ್‌ನಲ್ಲಿ ಆರು ಸಾವಿರ ಮರಗಳಿವೆ", romanized: "Kabban pārkinal·li āru sāvira maragaḷive", english: "There are six thousand trees in Cubbon Park" },
    context: "Bengaluru's trees are protected by law: cutting one requires serious justification",
    category: "nature",
  },
  {
    kannada: "ತಂಗಾಳಿ",
    transliteration: "Tangāḷi",
    meaning: "Cool breeze",
    example: { kannada: "ಸಂಜೆ ತಂಗಾಳಿ ಬೀಸುತ್ತೆ", romanized: "Sanje tangāḷi bīsutte", english: "A cool breeze blows in the evening" },
    context: "Bengaluru's evening tangāḷi is what makes rooftops the city's favourite hangout",
    category: "nature",
  },
  {
    kannada: "ಮೋಡ",
    transliteration: "Mōḍa",
    meaning: "Cloud",
    example: { kannada: "ಆಕಾಶದಲ್ಲಿ ಬಿಳಿ ಮೋಡ ಚೆಂದ", romanized: "Ākāśadal·li biḷi mōḍa chenda", english: "White clouds in the sky are beautiful" },
    context: "Pre-monsoon Bengaluru skies with dramatic mōḍa formations are breathtaking",
    category: "nature",
  },
  {
    kannada: "ತಿಂಡಿ",
    transliteration: "Thiṇḍi",
    meaning: "Breakfast / Snack",
    example: { kannada: "ತಿಂಡಿ ತಿಂದ್ಯಾ?", romanized: "Thiṇḍi thindyā?", english: "Have you had breakfast?" },
    context: "Asking about tindi is Bengaluru's love language: breakfast is serious business here",
    category: "food",
  },
  {
    kannada: "ಗೊತ್ತಿಲ್ಲ",
    transliteration: "Gottilla",
    meaning: "I don't know (used as a shrug/refusal)",
    example: { kannada: "ಯಾಕೆ ಹೀಗೆ? ಗೊತ್ತಿಲ್ಲ!", romanized: "Yāke hīge? Gottilla!", english: "Why is it like this? No idea!" },
    context: "The Bengaluru shrug: used with love when life doesn't make sense. Very common in tech offices.",
    category: "slang",
  },
  {
    kannada: "ನೋಡೋಣ",
    transliteration: "Nōḍōṇa",
    meaning: "Let's see / We'll figure it out",
    example: { kannada: "ಮೀಟಿಂಗ್ ಆದ ಮೇಲೆ ನೋಡೋಣ", romanized: "Mīṭing āda mēle nōḍōṇa", english: "Let's see after the meeting" },
    context: "The ultimate Bengaluru startup phrase: optimistic ambiguity",
    category: "slang",
  },
  {
    kannada: "ಹೋಗ್ ಬಿಡೋಣ",
    transliteration: "Hōg biḍōṇa",
    meaning: "Let's just go / Let it go",
    example: { kannada: "ಅದನ್ನ ಹೋಗ್ ಬಿಡೋಣ, ಹೊಸ ಪ್ಲಾನ್ ಮಾಡೋಣ", romanized: "Adanna hōg biḍōṇa, hosa plān māḍōṇa", english: "Let that go, let's make a new plan" },
    context: "Pure Bengaluru pragmatism: don't dwell, adapt, move forward",
    category: "slang",
  },
  {
    kannada: "ಚೆಂದ",
    transliteration: "Chenda",
    meaning: "Beautiful / Nice / Great",
    example: { kannada: "ಅದು ತುಂಬಾ ಚೆಂದ ಇದೆ", romanized: "Adu tumbā chenda ide", english: "That is very beautiful" },
    context: "Used more than 'cheluve' in everyday Bengaluru: simpler, warmer, more casual",
    category: "slang",
  },
  {
    kannada: "ಕೊಡಲಿ ಕಾವು ಕಾಡನ್ನೇ ನಾಶ ಮಾಡಿತು",
    transliteration: "Koḍali kāvu kāḍannē nāshamaḍitu",
    meaning: "The axe handle (from the forest) destroyed the forest itself",
    example: { kannada: "ಕೊಡಲಿ ಕಾವು ಕಾಡನ್ನೇ ನಾಶ ಮಾಡಿತು", romanized: "Koḍali kāvu kāḍannē nāśa māḍitu", english: "The axe made of wood destroyed the forest" },
    context: "Kannada proverb: Betrayal from within is the most destructive. A warning about ingratitude.",
    category: "proverb",
  },
  {
    kannada: "ಅತಿ ಆಸೆ ಗತಿ ಕೇಡು",
    transliteration: "Ati āse gati kēḍu",
    meaning: "Excess greed leads to ruin",
    example: { kannada: "ಅತಿ ಆಸೆ ಗತಿ ಕೇಡು: ಸಂತೋಷದಿಂದ ಬದುಕಿ", romanized: "Ati āse gati kēḍu: santoṣadinda baduki", english: "Too much greed ruins you: live with contentment" },
    context: "Ancient Kannada wisdom: the city's startup culture could use a reminder of this",
    category: "proverb",
  },
  {
    kannada: "ಒಳ್ಳೆಯ ಮಾತು ಒಳ್ಳೆಯ ಫಲ",
    transliteration: "Oḷḷeya mātu oḷḷeya phala",
    meaning: "Good words bring good results",
    example: { kannada: "ಒಳ್ಳೆಯ ಮಾತು ಒಳ್ಳೆಯ ಫಲ: ಯಾವಾಗಲೂ ಸತ್ಯ", romanized: "Oḷḷeya mātu oḷḷeya phala: yāvāgalū satya", english: "Good words bring good results: always true" },
    context: "Kannada folk wisdom: kindness in speech creates kindness in the world",
    category: "proverb",
  },
  {
    kannada: "ಸೂರ್ಯ",
    transliteration: "Sūrya",
    meaning: "Sun",
    example: { kannada: "ಸೂರ್ಯ ಉದಯ ತುಂಬಾ ಸುಂದರ", romanized: "Sūrya udaya tumbā sundara", english: "The sunrise is very beautiful" },
    context: "Bengaluru's sūrya rises gently: the city's mild climate makes every sunrise worth watching",
    category: "nature",
  },
  {
    kannada: "ಚಂದ್ರ",
    transliteration: "Chandra",
    meaning: "Moon",
    example: { kannada: "ಹುಣ್ಣಿಮೆ ಚಂದ್ರ ಚೆಲುವಾಗಿದೆ", romanized: "Huṇṇime chandra cheluvāgide", english: "The full moon is beautiful" },
    context: "Full moon nights over Bengaluru's lakes: a magic that never gets old",
    category: "nature",
  },
  {
    kannada: "ನಕ್ಷತ್ರ",
    transliteration: "Nakshatra",
    meaning: "Star",
    example: { kannada: "ಆಕಾಶದಲ್ಲಿ ನಕ್ಷತ್ರಗಳು ಹೊಳೆಯುತ್ತವೆ", romanized: "Ākāśadal·li nakṣatragaḷu hoḷeyuttave", english: "Stars shine in the sky" },
    context: "On clear winter nights, Bengaluru's skies still show their stars: worth looking up",
    category: "nature",
  },
  {
    kannada: "ಸಂಗೀತ",
    transliteration: "Sangīta",
    meaning: "Music",
    example: { kannada: "ಕರ್ನಾಟಕ ಸಂಗೀತ ಶ್ರೇಷ್ಠ", romanized: "Karnāṭaka sangīta śrēṣṭha", english: "Carnatic music is magnificent" },
    context: "Bengaluru is a centre of Carnatic music: the city that has kept an ancient tradition alive and vibrant",
    category: "culture",
  },
  {
    kannada: "ಕಲೆ",
    transliteration: "Kale",
    meaning: "Art",
    example: { kannada: "ಕನ್ನಡ ಕಲೆ ಶ್ರೀಮಂತ", romanized: "Kannaḍa kale śrīmanta", english: "Kannada art is rich" },
    context: "From ancient Hoysala sculptures to contemporary Bangalore art galleries: kale runs deep",
    category: "culture",
  },
  {
    kannada: "ನೃತ್ಯ",
    transliteration: "Nṛtya",
    meaning: "Dance",
    example: { kannada: "ಭರತನಾಟ್ಯ ನೃತ್ಯ ಸುಂದರ", romanized: "Bharatanāṭya nṛtya sundara", english: "Bharatanatyam dance is beautiful" },
    context: "Karnataka is home to Bharatanatyam and Yakshagana: ancient dance forms still thriving today",
    category: "culture",
  },
  {
    kannada: "ಹಬ್ಬ",
    transliteration: "Habba",
    meaning: "Festival",
    example: { kannada: "ದಸರಾ ಹಬ್ಬ ಮೈಸೂರಿನಲ್ಲಿ ಪ್ರಸಿದ್ಧ", romanized: "Dasarā habba maisūrinal·li prasiddha", english: "Dasara festival is famous in Mysore" },
    context: "Karnataka's festivals are magnificent: Dasara, Ugadi, Sankranti: the state knows how to celebrate",
    category: "culture",
  },
  {
    kannada: "ಮಳೆಗಾಲ",
    transliteration: "Maḷegāla",
    meaning: "Monsoon / Rainy season",
    example: { kannada: "ಮಳೆಗಾಲ ಬೆಂಗಳೂರಿನಲ್ಲಿ ಮೋಹಕ", romanized: "Maḷegāla bengaḷūrinal·li mōhaka", english: "Monsoon in Bengaluru is enchanting" },
    context: "True Bengalureans love maḷegāla: the smell of rain on hot earth (petrichor) is the city's signature scent",
    category: "nature",
  },
  {
    kannada: "ಚಳಿ",
    transliteration: "Chaḷi",
    meaning: "Cold / Chill",
    example: { kannada: "ಡಿಸೆಂಬರ್‌ನಲ್ಲಿ ಚಳಿ ಚೆಂದ", romanized: "Ḍisembar·nal·li chaḷi chenda", english: "The December chill is lovely" },
    context: "Bengaluru's winter at 15°C feels dramatic to locals: the city's most beloved season",
    category: "nature",
  },
  {
    kannada: "ಸ್ನೇಹ",
    transliteration: "Snēha",
    meaning: "Friendship / Warm affection",
    example: { kannada: "ನಮ್ಮ ಸ್ನೇಹ ಶಾಶ್ವತ", romanized: "Namma snēha śāśvata", english: "Our friendship is eternal" },
    context: "Snēha is deeper than friendship: it's the warmth of belonging, the spirit of Bengaluru itself",
    category: "everyday",
  },
  {
    kannada: "ಉದ್ಯಮ",
    transliteration: "Udyama",
    meaning: "Enterprise / Industry",
    example: { kannada: "ಬೆಂಗಳೂರು ಉದ್ಯಮದ ನಗರ", romanized: "Bengaḷūru udyamada nagara", english: "Bengaluru is a city of enterprise" },
    context: "From Infosys to Swiggy: udyama flows through Bengaluru's veins",
    category: "culture",
  },
  {
    kannada: "ಸಾಧನೆ",
    transliteration: "Sādhane",
    meaning: "Achievement / Accomplishment",
    example: { kannada: "ನಿಮ್ಮ ಸಾಧನೆ ಶ್ಲಾಘನೀಯ", romanized: "Nimma sādhane ślāghanīya", english: "Your achievement is commendable" },
    context: "From Olympic medals to IPO bell-rings: Bengaluru's sādhane inspires the nation",
    category: "culture",
  },
  {
    kannada: "ಜ್ಞಾನ",
    transliteration: "Jñāna",
    meaning: "Knowledge / Wisdom",
    example: { kannada: "ಜ್ಞಾನ ಶಕ್ತಿ", romanized: "Jñāna śakti", english: "Knowledge is power" },
    context: "Bengaluru's universities and research institutions make it India's capital of jñāna",
    category: "culture",
  },
  {
    kannada: "ಅಮೃತ",
    transliteration: "Amṛta",
    meaning: "Nectar / Immortal essence",
    example: { kannada: "ಮಳೆ ಭೂಮಿಗೆ ಅಮೃತ", romanized: "Maḷe bhūmige amṛta", english: "Rain is nectar for the earth" },
    context: "Rain as amṛta: Bengaluru's monsoons bring life to lakes, gardens, and spirits",
    category: "nature",
  },
  {
    kannada: "ಆನಂದ",
    transliteration: "Ānanda",
    meaning: "Joy / Bliss",
    example: { kannada: "ಕಬ್ಬನ್ ಪಾರ್ಕ್‌ನಲ್ಲಿ ಆನಂದ ಇದೆ", romanized: "Kabban pārkinal·li ānanda ide", english: "There is joy in Cubbon Park" },
    context: "The ānanda of a Sunday morning in Bengaluru: filter coffee, green park, good company",
    category: "everyday",
  },
  {
    kannada: "ಸಂತೋಷ",
    transliteration: "Santosha",
    meaning: "Happiness / Contentment",
    example: { kannada: "ನಿಮಗೆ ಸಂತೋಷ ಆಗಲಿ", romanized: "Nimage santoṣa āgali", english: "May you be happy" },
    context: "The Kannada blessing: Bengaluru gives this freely to all who come here",
    category: "everyday",
  },
  {
    kannada: "ಧೈರ್ಯ",
    transliteration: "Dhairya",
    meaning: "Courage / Bravery",
    example: { kannada: "ಧೈರ್ಯದಿಂದ ಮುಂದೆ ಹೋಗು", romanized: "Dhairyādinda munde hōgu", english: "Go forward with courage" },
    context: "Every founder who started a company in a garage had dhairya: Bengaluru's founding spirit",
    category: "culture",
  },
  {
    kannada: "ಪ್ರೀತಿ",
    transliteration: "Prīti",
    meaning: "Love / Affection",
    example: { kannada: "ಬೆಂಗಳೂರಿನ ಮೇಲೆ ಪ್ರೀತಿ", romanized: "Bengaḷūrina mēle prīti", english: "Love for Bengaluru" },
    context: "What this portal is built on: pure prīti for the city",
    category: "everyday",
  },
  {
    kannada: "ನದಿ",
    transliteration: "Nadi",
    meaning: "River",
    example: { kannada: "ಅರ್ಕಾವತಿ ನದಿ ಸುಂದರ", romanized: "Arkāvati nadi sundara", english: "The Arkavathi river is beautiful" },
    context: "The rivers that once fed Bangalore's thousand lakes are slowly being restored",
    category: "nature",
  },
  {
    kannada: "ಗುಡ್ಡ",
    transliteration: "Gudda",
    meaning: "Hill",
    example: { kannada: "ನಂದಿ ಗುಡ್ಡ ತಂಪಾಗಿದೆ", romanized: "Nandi guḍḍa tampāgide", english: "Nandi Hill is cool and pleasant" },
    context: "Bengaluru sits on a plateau: surrounded by beautiful gudda on all sides",
    category: "nature",
  },
  {
    kannada: "ಕೆಲಸ",
    transliteration: "Kelasa",
    meaning: "Work",
    example: { kannada: "ಕೆಲಸ ಚೆನ್ನಾಗಿ ನಡೆಯುತ್ತಿದೆ", romanized: "Kelasa chennāgi naḍeyuttide", english: "Work is going well" },
    context: "Bengaluru's kelasa ethic built a tech ecosystem envied by the world",
    category: "everyday",
  },
  {
    kannada: "ಗೆಳತಿ",
    transliteration: "Geḷati",
    meaning: "Friend (feminine)",
    example: { kannada: "ನನ್ನ ಗೆಳತಿ ತುಂಬಾ ಒಳ್ಳೆಯವಳು", romanized: "Nanna geḷati tumbā oḷḷeyavaḷu", english: "My friend is very kind" },
    context: "The bonds formed in Bengaluru last a lifetime: this city builds deep friendships",
    category: "everyday",
  },
  {
    kannada: "ನಂಬಿಕೆ",
    transliteration: "Nambike",
    meaning: "Trust / Faith / Belief",
    example: { kannada: "ನಂಬಿಕೆ ಮುಖ್ಯ", romanized: "Nambike mukhya", english: "Trust is important" },
    context: "Bengaluru's startup ecosystem runs on nambike: investors trusting founders, founders trusting teams",
    category: "culture",
  },
  {
    kannada: "ಸೇವೆ",
    transliteration: "Sēve",
    meaning: "Service / Selfless giving",
    example: { kannada: "ಸಮಾಜಕ್ಕೆ ಸೇವೆ ಮಾಡಿ", romanized: "Samājakse sēve māḍi", english: "Serve your community" },
    context: "Bengaluru's lake restoration volunteers, park maintainers: sēve is the city's quiet superpower",
    category: "culture",
  },
  {
    kannada: "ಹೊಳೆ",
    transliteration: "Hoḷe",
    meaning: "Stream / To shine / To gleam",
    example: { kannada: "ಕೆರೆ ನೀರು ಹೊಳೆಯುತ್ತದೆ", romanized: "Kere nīru hoḷeyuttade", english: "The lake water gleams" },
    context: "Bengaluru's restored lakes hoḷe in the morning sun: a sign of the city's renewal",
    category: "nature",
  },
  {
    kannada: "ಅಡ್ಜಸ್ಟ್ ಮಾಡಿ",
    transliteration: "Adjust Māḍi",
    meaning: "Adjust / Go with the flow / Make it work",
    example: { kannada: "ಟ್ರಾಫಿಕ್ ಇದೆ, ಅಡ್ಜಸ್ಟ್ ಮಾಡಿ!", romanized: "Trāphik ide, adjust māḍi!", english: "There's traffic, just adjust!" },
    context: "The most Bangalorean phrase ever: the city's philosophy of joyful resilience. This portal is named after it.",
    category: "slang",
  },
  {
    kannada: "ಬೆಚ್ಚಗೆ",
    transliteration: "Beccage",
    meaning: "Warm / Cozy",
    example: { kannada: "ಮನೆ ತುಂಬಾ ಬೆಚ್ಚಗೆ ಇದೆ", romanized: "Mane tumbā beccage ide", english: "The home is very warm and cozy" },
    context: "The feeling of a Bengaluru morning indoors with filter coffee: pure beccage",
    category: "everyday",
  },
  {
    kannada: "ಲೇ",
    transliteration: "Lē",
    meaning: "Hey! (casual address, friendly)",
    example: { kannada: "ಲೇ, ಎಲ್ಲಿ ಹೋಗ್ತಿಯಾ?", romanized: "Lē, el·li hōgtiyā?", english: "Hey, where are you going?" },
    context: "Pure Bengaluru street warmth: the way friends hail each other across a street",
    category: "slang",
  },
  {
    kannada: "ಬೇಕಿತ್ತ",
    transliteration: "Bēkitta",
    meaning: "I needed this / This was required",
    example: { kannada: "ಒಂದು ಕಾಫಿ ಬೇಕಿತ್ತ", romanized: "Ondu kāphi bēkitta", english: "I needed a coffee" },
    context: "The relief of a needed filter coffee: Bengaluru's most relatable phrase",
    category: "slang",
  },
  {
    kannada: "ಅಕ್ಕ",
    transliteration: "Akka",
    meaning: "Elder sister (also a respectful address to any older woman)",
    example: { kannada: "ಅಕ್ಕ, ಒಂದು ದೋಸೆ ಕೊಡಿ", romanized: "Akka, ondu dōse koḍi", english: "Sister, please give me one dosa" },
    context: "In Bengaluru, you address any shop owner, auto driver's wife, or helpful stranger as 'akka'. The city runs on this warmth.",
    category: "everyday",
  },
  {
    kannada: "ಅಣ್ಣ",
    transliteration: "Anna",
    meaning: "Elder brother (also a respectful address to any older man)",
    example: { kannada: "ಅಣ್ಣ, ಮೀಟರ್ ಹಾಕಿ", romanized: "Aṇṇa, mīṭar hāki", english: "Brother, start the meter please" },
    context: "Call any auto driver, shopkeeper, or kind stranger 'anna' in Bengaluru and doors open. It means you respect them.",
    category: "everyday",
  },
  {
    kannada: "ಸ್ವಚ್ಛ",
    transliteration: "Swachha",
    meaning: "Clean / Pure / Spotless",
    example: { kannada: "ಕಬ್ಬನ್ ಪಾರ್ಕ್ ತುಂಬಾ ಸ್ವಚ್ಛ", romanized: "Kabban pārk tumbā svachcha", english: "Cubbon Park is very clean" },
    context: "The word Bengaluru's lake restoration volunteers repeat: every clean lake, every swept footpath is a small act of swachha",
    category: "nature",
  },
  {
    kannada: "ಪ್ರಕೃತಿ",
    transliteration: "Prakriti",
    meaning: "Nature / The natural world",
    example: { kannada: "ಪ್ರಕೃತಿ ನಮ್ಮ ಸ್ನೇಹಿತ", romanized: "Prakṛti namma snēhita", english: "Nature is our friend" },
    context: "Bengaluru's relationship with prakriti is its defining quality: a city that builds sky scrapers but still has forests inside it",
    category: "nature",
  },
  {
    kannada: "ನಕ್ಷೆ",
    transliteration: "Nakshe",
    meaning: "Map",
    example: { kannada: "ಬೆಂಗಳೂರಿನ ನಕ್ಷೆ ತೋರಿಸು", romanized: "Bengaḷūrina nakṣe tōrisu", english: "Show me the map of Bengaluru" },
    context: "Bengaluru's lake map is a story of the city's past glory: over a thousand lakes once covered the plateau",
    category: "culture",
  },
  {
    kannada: "ಊರು",
    transliteration: "Ooru",
    meaning: "Town / One's native place / Home",
    example: { kannada: "ನಿಮ್ಮ ಊರು ಯಾವುದು?", romanized: "Nimma ūru yāvudu?", english: "What is your hometown?" },
    context: "Ask any Bangalorean 'ooru yaavudu?' and you'll hear thirty different places. The city is everyone's adopted home.",
    category: "everyday",
  },
  {
    kannada: "ಬೀದಿ",
    transliteration: "Beedi",
    meaning: "Street / Lane / Road",
    example: { kannada: "ಆ ಬೀದಿಯಲ್ಲಿ ಒಳ್ಳೆ ದೋಸೆ ಸಿಗುತ್ತೆ", romanized: "Ā bīdiyal·li oḷḷe dōse sigutte", english: "You'll find great dosas on that street" },
    context: "Every Bangalore beedi has its own personality: the beedis of Basavanagudi feel 50 years removed from those of Koramangala",
    category: "everyday",
  },
  {
    kannada: "ಸಂಸ್ಕೃತಿ",
    transliteration: "Samskriti",
    meaning: "Culture / Civilisation / Heritage",
    example: { kannada: "ಕನ್ನಡ ಸಂಸ್ಕೃತಿ ಶ್ರೀಮಂತ", romanized: "Kannaḍa samskṛti śrīmanta", english: "Kannada culture is rich" },
    context: "2,000 years of Kannada samskriti: literature, music, dance, temple architecture, cuisine, and a warmth the world is still discovering",
    category: "culture",
  },
  {
    kannada: "ಇಳಿ",
    transliteration: "Ili",
    meaning: "Descend / Come down / Alight",
    example: { kannada: "ಮೆಟ್ರೋದಲ್ಲಿ ಇಲ್ಲಿ ಇಳಿ", romanized: "Meṭrōdal·li il·li iḷi", english: "Get off the Metro here" },
    context: "The word that launched a thousand Namma Metro journeys: Bengaluru finally went underground and grew up",
    category: "everyday",
  },
  {
    kannada: "ಚಳುವಳಿ",
    transliteration: "Chaluvali",
    meaning: "Movement / Protest / Campaign",
    example: { kannada: "ಕನ್ನಡ ರಾಜ್ಯೋತ್ಸವ ಚಳುವಳಿ", romanized: "Kannaḍa rājyōtsava chaḷuvaḷi", english: "The Karnataka Rajyotsava movement" },
    context: "Bengaluru's citizens are known for their chaluvali spirit: lake restoration, tree protection, traffic reform. The city fights for what it loves.",
    category: "culture",
  },
  {
    kannada: "ಹೆಮ್ಮೆ",
    transliteration: "Hemme",
    meaning: "Pride",
    example: { kannada: "ನನಗೆ ಬೆಂಗಳೂರಿನ ಮೇಲೆ ಹೆಮ್ಮೆ", romanized: "Nanage bengaḷūrina mēle hemme", english: "I am proud of Bengaluru" },
    context: "Namma Bengaluru: the hemme of 12 million people who chose this city, built it, and refuse to give up on it",
    category: "culture",
  },
  {
    kannada: "ಕಲ್ಲು",
    transliteration: "Kallu",
    meaning: "Stone / Rock",
    example: { kannada: "ಲಾಲ್‌ಬಾಗ್‌ನ ಕಲ್ಲು ತುಂಬಾ ಹಳೆಯದು", romanized: "Lālbāgna kallu tumbā haḷeyadu", english: "The rock in Lalbagh is very ancient" },
    context: "The rock in Lalbagh is 3,000 million years old. Bangalore literally stands on some of the oldest exposed stone on Earth.",
    category: "nature",
  },
  {
    kannada: "ಹಬ್ಬದೂಟ",
    transliteration: "Habbadoota",
    meaning: "Festive meal / A feast",
    example: { kannada: "ಮನೆಯಲ್ಲಿ ಹಬ್ಬದೂಟ ಆಯ್ತು", romanized: "Maneyalli habbadūṭa āytu", english: "We had a festive feast at home" },
    context: "A Kannada habbadoota: rice, sambar, rasam, palya, kosambari, payasa, served on a banana leaf. The flavours of home.",
    category: "food",
  },
  {
    kannada: "ಬಿಸಿ ಬೇಳೆ ಬಾತ್",
    transliteration: "Bisibelebath",
    meaning: "Hot lentil rice: a signature Karnataka dish",
    example: { kannada: "ಬಿಸಿ ಬೇಳೆ ಬಾತ್ ಬಿಸಿ ಬಿಸಿ ತಿನ್ನಿ", romanized: "Bisi bēḷe bāt bisi bisi tinni", english: "Eat the bisibelebath while it's hot" },
    context: "MTR's bisibelebath has been on the menu since 1924. Some recipes should never change.",
    category: "food",
  },
  {
    kannada: "ಉಳಿ",
    transliteration: "Uli",
    meaning: "Chisel / To carve",
    example: { kannada: "ಶಿಲ್ಪಿ ಕಲ್ಲನ್ನು ಉಳಿಯಿಂದ ಕೆತ್ತಿದ", romanized: "Śilpi kallanu uḷiyinda kettida", english: "The sculptor carved the stone with a chisel" },
    context: "The Hoysala temples of Karnataka were carved with an uli by artisans who spent their entire lives on a single pillar. Patience as a philosophy.",
    category: "culture",
  },
  {
    kannada: "ಪೇಟೆ",
    transliteration: "Pete",
    meaning: "Market / Bazaar / Commercial area",
    example: { kannada: "ಕೆ.ಆರ್. ಪೇಟೆಗೆ ಹೋಗೋಣ", romanized: "Ke.Ār. pēṭege hōgōṇa", english: "Let's go to K.R. Market" },
    context: "Bengaluru's pete areas (Chickpete, Balepete, KR Pete) are the old city's beating commercial heart: a riot of colour, flowers, silk, and spice",
    category: "culture",
  },
  {
    kannada: "ಓಣಿ",
    transliteration: "Oni",
    meaning: "Lane / Neighbourhood alley",
    example: { kannada: "ನಮ್ಮ ಓಣಿಯ ಗಣಪತಿ ಹಬ್ಬ ತುಂಬಾ ಚೆಂದ", romanized: "Namma ōṇiya gaṇapati habba tumbā chenda", english: "The Ganesha festival in our lane is very beautiful" },
    context: "Every Bengaluru oni has its own character, its own tea stall, its own gossip. The city's soul lives in the lanes, not the highways.",
    category: "everyday",
  },
];
