export interface HistoricalEvent {
  month: number;
  day: number;
  title: string;
  description: string;
  year?: number;
  emoji?: string;
}

export const BENGALURU_HISTORY: HistoricalEvent[] = [
  {
    month: 1,
    day: 26,
    title: "Republic Day Flower Show",
    description: "Lalbagh's legendary flower show opens, a 60-year tradition of botanical beauty that draws hundreds of thousands of visitors",
    emoji: "🌸",
  },
  {
    month: 3,
    day: 15,
    title: "Lalbagh Founded",
    year: 1760,
    description: "Hyder Ali began the garden that would become one of Asia's finest botanical parks: 260+ years of living legacy",
    emoji: "🌿",
  },
  {
    month: 4,
    day: 14,
    title: "Ugadi: Kannada New Year",
    description: "Karnataka's new year begins with pachadi: the six tastes of life, eaten together as a reminder that life holds all flavours",
    emoji: "🎊",
  },
  {
    month: 5,
    day: 22,
    title: "Kempegowda Day",
    description: "Honoring Bengaluru's founder Kempe Gowda I, who built the city's first mud fort in 1537: the seed from which a great city grew",
    year: 1537,
    emoji: "🏰",
  },
  {
    month: 6,
    day: 12,
    title: "Infosys IPO",
    year: 1993,
    description: "Infosys listed on Indian exchanges: the moment that told the world: Indian IT has arrived. The Silicon Valley of the East was born.",
    emoji: "🚀",
  },
  {
    month: 7,
    day: 15,
    title: "Monsoon Arrives in Bengaluru",
    description: "Average date when Bengaluru's beloved rains begin: the city breathes again, petrichor fills the air, and everyone smiles",
    emoji: "🌧️",
  },
  {
    month: 8,
    day: 15,
    title: "Independence Day Flower Show",
    description: "Lalbagh's second flower show of the year: gardens in full monsoon glory, bursting with color after the rains",
    emoji: "🌺",
  },
  {
    month: 9,
    day: 1,
    title: "Vidhana Soudha Inauguration",
    year: 1956,
    description: "Karnataka's parliament opened: the 'Pride of Karnataka' still stands magnificent, a blend of Dravidian and Kannada architecture",
    emoji: "🏛️",
  },
  {
    month: 10,
    day: 2,
    title: "Dasara Celebrations Begin",
    description: "Ten days of celebration begin: Mysore Dasara is the state's grandest festival, declared the 'Nadahabba' (state festival) of Karnataka",
    emoji: "🐘",
  },
  {
    month: 11,
    day: 1,
    title: "Karnataka Rajyotsava",
    year: 1956,
    description: "Statehood Day: Karnataka was unified on November 1st, 1956. The entire state turns red and yellow. Jai Karnataka!",
    emoji: "🟡",
  },
  {
    month: 11,
    day: 18,
    title: "Namma Metro First Run",
    year: 2011,
    description: "Bengaluru's Metro made its first journey: the city went underground and grew up. Now connecting millions every day.",
    emoji: "🚇",
  },
  {
    month: 12,
    day: 25,
    title: "Church Street at Christmas",
    description: "Bengaluru's cosmopolitan spirit shines: Christmas is celebrated city-wide, with Church Street lit up like a festival of light",
    emoji: "✨",
  },
  {
    month: 1,
    day: 9,
    title: "IISc Founded",
    year: 1909,
    description: "The Indian Institute of Science opened in Bengaluru, fulfilling a vision of Jamsetji Tata and Swami Vivekananda. It remains India's finest research institution and a global centre of scientific excellence.",
    emoji: "🔬",
  },
  {
    month: 2,
    day: 28,
    title: "Raman Effect Announced",
    year: 1928,
    description: "C.V. Raman announced his discovery of the Raman Effect at IISc Bengaluru. Two years later he became India's first Nobel laureate. We celebrate National Science Day on this date.",
    emoji: "💡",
  },
  {
    month: 3,
    day: 10,
    title: "HAL Established",
    year: 1940,
    description: "Hindustan Aeronautics Limited was founded in Bengaluru, making the city the heart of India's aerospace industry. HAL has since built fighter jets, helicopters, and spacecraft.",
    emoji: "✈️",
  },
  {
    month: 5,
    day: 11,
    title: "India's First IT Park Opens",
    year: 1991,
    description: "Software Technology Parks of India opened its first node in Bengaluru, the official launchpad of India's software export industry. The Silicon Valley of the East story begins here.",
    emoji: "💻",
  },
  {
    month: 6,
    day: 1,
    title: "Bengaluru Renamed",
    year: 2006,
    description: "The Government of Karnataka officially renamed Bangalore to Bengaluru, restoring the city's original Kannada name. The name derives from 'Benda Kaluru': the town of boiled beans.",
    emoji: "📜",
  },
  {
    month: 7,
    day: 28,
    title: "Kuvempu's Birthday",
    year: 1904,
    description: "Karnataka's poet laureate Kuvempu was born on this day. His poem 'Jaya Bharata Jananiya Tanujate' is Karnataka's beloved state anthem. He championed a universal human identity beyond caste and religion.",
    emoji: "✍️",
  },
  {
    month: 8,
    day: 12,
    title: "Dr. Rajkumar's Birthday",
    year: 1929,
    description: "The beloved Kannada film legend was born in Singanallur. Rajkumar became more than an actor: he was the cultural soul of Karnataka. His voice and humility are a permanent part of the city's heart.",
    emoji: "🎬",
  },
  {
    month: 9,
    day: 15,
    title: "Engineers' Day",
    year: 1860,
    description: "India celebrates Engineers' Day on the birthday of M. Visvesvaraya, Bengaluru's great engineer-statesman. He designed the flood defences of Hyderabad and the KRS dam, and served as Dewan of Mysore.",
    emoji: "⚙️",
  },
  {
    month: 10,
    day: 22,
    title: "Chandrayaan-1 Launched",
    year: 2008,
    description: "India's first lunar mission launched from ISRO's Bengaluru headquarters. Chandrayaan-1 confirmed water on the Moon: a discovery that made Bengaluru the space capital of Asia.",
    emoji: "🌕",
  },
  {
    month: 12,
    day: 10,
    title: "C.V. Raman's Nobel Prize",
    year: 1930,
    description: "C.V. Raman received the Nobel Prize in Physics for his discovery of the Raman Effect, made right here at IISc Bengaluru. India's first Nobel Prize in science, won by a man who worked in this city.",
    emoji: "🏅",
  },
];

export const WIKIPEDIA_ARTICLES = [
  "History_of_Bangalore",
  "Vidhana_Soudha",
  "Lalbagh_Botanical_Garden",
  "Bangalore_Palace",
  "Tipu_Sultan%27s_Summer_Palace",
  "Cubbon_Park",
  "Kannada_language",
  "Karnataka_cuisine",
  "Indian_Institute_of_Science",
  "Kempe_Gowda_I",
  "Mysore_Dasara",
  "Nandi_Hills,_Chikkaballapur",
  "Bangalore_Metro",
  "Carnatic_music",
  "Infosys",
  "Bannerghatta_National_Park",
];
